<script setup lang="ts">
defineProps<{ activePage: string; theme: "system" | "light" | "dark" }>();
defineEmits<{ select: [page: string]; toggleTheme: [] }>();
const links = [{id:"orders",label:"订单中心",icon:"▣"},{id:"inventory",label:"商品库存",icon:"☷"},{id:"members",label:"会员管理",icon:"⌖"},{id:"reports",label:"销售报表",icon:"▥"}];
</script>
<template><header class="header"><div class="logo">Moe<span>Cr</span></div><button v-for="link in links" :key="link.id" class="header-link" :class="{active:activePage===link.id}" @click="$emit('select',link.id)"><i>{{link.icon}}</i>{{link.label}}</button><div class="user-info"><button class="theme-toggle" :aria-label="`切换主题，当前为${theme}`" @click="$emit('toggleTheme')">{{ theme === "system" ? "◐" : theme === "light" ? "☀" : "☾" }}</button><button class="scope">全部 <b>⌄</b></button><span class="user-name">MoeCraft</span><span class="profile">◉</span><time>08:20 pm</time></div></header></template>
<style scoped>
.header{position:relative;z-index:1;display:flex;width:100%;min-height:72px;align-items:center;padding:0 clamp(17px,2.4vw,30px);border-bottom:1px solid var(--border);background:var(--surface);box-shadow:0 5px 16px rgb(39 49 80 / 6%);white-space:nowrap;animation:top 1s both}.logo{padding:20px clamp(18px,4vw,50px) 20px 0;color:var(--text);font-size:16px}.logo span{margin-left:-2px;padding:8px;border-radius:50%;background:var(--accent);color:white;font-size:15px}.header-link{display:flex;align-items:center;align-self:stretch;padding:20px;border:0;border-bottom:3px solid transparent;background:transparent;color:var(--text-muted);font-size:15px;cursor:pointer}.header-link i{margin-right:14px;font-style:normal;font-size:19px}.header-link.active,.header-link:hover{border-bottom-color:var(--accent);background:var(--accent-soft);color:var(--text)}.user-info{display:flex;align-items:center;margin-left:auto}.theme-toggle,.scope{display:flex;align-items:center;gap:10px;margin-right:12px;padding:5px 12px;border:1px solid var(--border);border-radius:4px;background:var(--surface-raised);color:var(--text-secondary);cursor:pointer}.theme-toggle{width:32px;height:32px;justify-content:center;padding:0}.scope{margin-right:20px}.scope b{font-size:14px}.profile{width:18px;margin:0 20px 0 12px;color:var(--text-secondary);font-size:18px}.user-info time{font-size:13px}@keyframes top{from{transform:translateY(-30px);opacity:0}to{transform:none;opacity:1}}@media(max-width:1060px){.scope,.user-info time{display:none}}@media(max-width:930px){.header-link{display:none}.profile{margin-right:0}}@media(max-width:520px){.header{padding:0 17px}.logo{padding-right:18px}.user-name{font-size:13px}.theme-toggle{margin-right:8px}}
</style>
