<script setup lang="ts">
import type { MessageKey } from "../i18n";
import { useLocale } from "../i18n";
defineProps<{ activePage: string }>();
defineEmits<{ select: [page: string] }>();
const { t } = useLocale();
type NavItem = { id: string; label: MessageKey; icon: string; section?: "bottom" };
const items: NavItem[] = [
  { id: "overview", label: "nav.overview", icon: "⌂" }, { id: "onboarding", label: "nav.onboarding", icon: "◇" }, { id: "products", label: "nav.products", icon: "▦" }, { id: "inventory", label: "nav.inventory", icon: "▤" }, { id: "orders", label: "nav.orders", icon: "▣" }, { id: "afterSales", label: "nav.afterSales", icon: "↩" }, { id: "members", label: "nav.members", icon: "♙" }, { id: "reports", label: "nav.reports", icon: "⌁" }, { id: "settings", label: "nav.settings", icon: "⚙", section: "bottom" }
];
</script>
<template><aside class="sidebar"><div class="brand"><span>M</span><div><b>MoeCraft</b><small>MERCHANT</small></div></div><nav aria-label="后台主导航"><button v-for="item in items" :key="item.id" :class="[{active:activePage===item.id},{bottom:item.section==='bottom'}]" :aria-current="activePage===item.id?'page':undefined" @click="$emit('select',item.id)"><i>{{item.icon}}</i><span>{{t(item.label)}}</span><em v-if="item.id==='onboarding'" /></button></nav><div class="version"><span>MC</span><div><b>Console</b><small>v0.11</small></div></div></aside></template>
<style scoped>.sidebar{display:flex;width:224px;height:100%;flex-direction:column;flex-shrink:0;padding:18px 14px;border-right:1px solid var(--border);background:var(--surface)}.brand{display:flex;align-items:center;gap:11px;padding:4px 8px 22px}.brand>span{display:grid;width:38px;height:38px;place-items:center;border-radius:12px;background:linear-gradient(145deg,#6957e8,#9d6be7);box-shadow:0 8px 16px rgb(105 87 232 / 22%);color:#fff;font-size:19px;font-weight:700}.brand div,.version div{display:grid}.brand b{color:var(--text);font-size:15px}.brand small,.version small{color:var(--text-muted);font-size:8px;letter-spacing:.16em}nav{display:flex;min-height:0;flex:1;flex-direction:column;gap:4px;overflow:auto}nav button{position:relative;display:flex;width:100%;min-height:43px;align-items:center;gap:12px;padding:0 12px;border:0;border-radius:10px;background:transparent;color:var(--text-muted);font-size:12px;text-align:left;cursor:pointer;transition:.18s}nav button:hover{background:var(--surface-raised);color:var(--text)}nav button.active{background:linear-gradient(100deg,color-mix(in srgb,#6957e8 14%,var(--surface)),color-mix(in srgb,#6957e8 6%,var(--surface)));color:#6957e8;font-weight:650}nav button.active::before{position:absolute;width:3px;height:21px;left:0;border-radius:0 3px 3px 0;background:#6957e8;content:""}nav button i{display:grid;width:22px;place-items:center;font-size:17px;font-style:normal}nav button em{width:6px;height:6px;margin-left:auto;border-radius:50%;background:#ef7388;box-shadow:0 0 0 3px var(--danger-soft)}nav button.bottom{margin-top:auto}.version{display:flex;align-items:center;gap:9px;padding:12px;margin-top:12px;border-radius:10px;background:var(--surface-raised)}.version>span{display:grid;width:27px;height:27px;place-items:center;border-radius:8px;background:var(--accent-soft);color:var(--accent);font-size:9px;font-weight:700}.version b{color:var(--text-secondary);font-size:10px}@media(max-width:860px){.sidebar{width:68px;padding:14px 9px}.brand{padding:4px 6px 20px}.brand div,.version{display:none}nav button{justify-content:center;padding:0}nav button span{display:none}nav button em{position:absolute;right:5px;top:7px}}
</style>
