<script setup lang="ts">
import { computed, onMounted, reactive, ref } from "vue";
import type { MerchantApplicationStatus, MerchantApplicationView, UserRole } from "@moecraft/shared";
import { apiRequest } from "../api";

const props = defineProps<{ roles: UserRole[] }>();
const reviewer = computed(() => props.roles.some((role) => role.startsWith("PLATFORM_")));
const loading = ref(true), busy = ref(false), error = ref(""), message = ref("");
const mine = ref<MerchantApplicationView | null>(null), queue = ref<MerchantApplicationView[]>([]), selected = ref<MerchantApplicationView | null>(null);
const comment = ref("");
const form = reactive({ companyName:"", contactName:"", contactPhone:"", contactEmail:"", businessLicenseNumber:"", qualificationFileIds:[] as string[], agreementAccepted:false });
const labels: Record<MerchantApplicationStatus,string> = { DRAFT:"草稿",SUBMITTED:"待审核",NEEDS_CHANGES:"待补件",APPROVED:"已通过",REJECTED:"已拒绝",WITHDRAWN:"已撤回" };
const reasonTemplates = ["资质文件不清晰，请重新上传", "企业信息与资质文件不一致", "缺少品牌或版权授权证明"];
const editable = computed(() => !mine.value || ["DRAFT","NEEDS_CHANGES","REJECTED","WITHDRAWN"].includes(mine.value.status));

function copy(item: MerchantApplicationView) { Object.assign(form, { ...item, qualificationFileIds:[...item.qualificationFileIds] }); }
async function load() { loading.value=true; error.value=""; try { if(reviewer.value) queue.value=await apiRequest<MerchantApplicationView[]>("/merchant-applications"); else { mine.value=await apiRequest<MerchantApplicationView|null>("/merchant-applications/mine"); if(mine.value) copy(mine.value); } } catch { error.value="加载失败，请确认 API 已启动。"; } finally { loading.value=false; } }
async function addFiles(files: FileList|null) { for(const file of Array.from(files??[])) try { const asset=await apiRequest<{id:string}>("/files",{method:"POST",body:JSON.stringify({purpose:"merchant-qualification",fileName:file.name,mimeType:file.type,sizeBytes:file.size})}); form.qualificationFileIds.push(asset.id); } catch { error.value=`${file.name} 类型或大小不合规。`; } }
async function save() { busy.value=true;error.value="";try{mine.value=await apiRequest<MerchantApplicationView>("/merchant-applications/mine",{method:"PUT",body:JSON.stringify(form)});copy(mine.value);message.value="草稿已保存。";}catch{error.value="保存失败，请检查全部字段。";}finally{busy.value=false;} }
async function applicantAction(action:"submit"|"withdraw") { busy.value=true;error.value="";try{mine.value=await apiRequest<MerchantApplicationView>(`/merchant-applications/mine/${action}`,{method:"POST"});message.value=action==="submit"?"已提交审核。":"已撤回。";}catch{error.value="操作失败，请检查申请状态和资料完整性。";}finally{busy.value=false;} }
async function review(decision:"APPROVE"|"REJECT"|"REQUEST_CHANGES") { if(!selected.value)return;busy.value=true;error.value="";try{await apiRequest(`/merchant-applications/${selected.value.id}/review`,{method:"POST",body:JSON.stringify({decision,comment:comment.value||undefined})});selected.value=null;comment.value="";message.value="审核结果已保存。";await load();}catch{error.value="审核失败；拒绝或补件必须填写原因。";}finally{busy.value=false;} }
async function merchantStatus(status:"ACTIVE"|"SUSPENDED") { if(!selected.value)return;busy.value=true;try{await apiRequest(`/merchant-applications/${selected.value.id}/merchant-status`,{method:"POST",body:JSON.stringify({status,reason:comment.value||"平台运营状态调整"})});message.value=status==="ACTIVE"?"商家已启用。":"商家已停用。";await load();selected.value=queue.value.find((item)=>item.id===selected.value?.id)??null;}catch{error.value="商家状态调整失败。";}finally{busy.value=false;} }
onMounted(load);
</script>

<template><section class="onboarding content-scroll">
  <header><div><small>MERCHANT ONBOARDING</small><h1>{{reviewer?"商家入驻审核":"申请成为 MoeCraft 商家"}}</h1><p>{{reviewer?"审核资料并记录完整时间线。":"平台通过后，账号将自动获得店主身份。"}}</p></div><button class="muted" @click="load">刷新</button></header>
  <p v-if="error" class="notice error" role="alert">{{error}}</p><p v-if="message" class="notice success">{{message}}</p><div v-if="loading" class="notice">正在加载…</div>
  <template v-else-if="reviewer"><div v-if="!queue.length" class="notice">暂无待审核申请。</div><div v-else class="queue"><button v-for="item in queue" :key="item.id" class="card" @click="selected=item"><b>{{item.companyName}}</b><span>{{item.contactName}} · {{item.contactEmail}}</span><em>{{labels[item.status]}}</em></button></div>
    <article v-if="selected" class="panel"><h2>{{selected.companyName}}</h2><p>执照号：{{selected.businessLicenseNumber}}</p><p>联系人：{{selected.contactName}} / {{selected.contactPhone}}</p><p>资质文件：{{selected.qualificationFileIds.length}} 份</p><p v-if="selected.merchantStatus">商家状态：{{selected.merchantStatus==='ACTIVE'?'营业中':'已停用'}}</p><ol><li v-for="event in selected.timeline" :key="event.id">{{labels[event.toStatus]}} · {{new Date(event.createdAt).toLocaleString()}} {{event.comment}}</li></ol><label>审核意见<textarea v-model="comment" rows="3" placeholder="拒绝或补件时必填"/></label><div v-if="selected.status==='SUBMITTED'" class="templates"><button v-for="reason in reasonTemplates" :key="reason" class="muted" @click="comment=reason">{{reason}}</button></div><div v-if="selected.status==='SUBMITTED'" class="actions"><button class="muted" @click="review('REQUEST_CHANGES')">要求补件</button><button class="danger" @click="review('REJECT')">拒绝</button><button @click="review('APPROVE')">通过</button></div><div v-if="selected.status==='APPROVED'" class="actions"><button v-if="selected.merchantStatus==='SUSPENDED'" @click="merchantStatus('ACTIVE')">启用商家</button><button v-else class="danger" @click="merchantStatus('SUSPENDED')">停用商家</button></div></article>
  </template>
  <template v-else><p v-if="mine" class="notice">当前状态：<b>{{labels[mine.status]}}</b><span v-if="mine.reviewComment">　审核意见：{{mine.reviewComment}}</span></p><form class="panel form" @submit.prevent="save"><label>企业/工作室名称<input v-model="form.companyName" :disabled="!editable" required minlength="2"/></label><label>联系人<input v-model="form.contactName" :disabled="!editable" required minlength="2"/></label><label>联系电话<input v-model="form.contactPhone" :disabled="!editable" required minlength="6"/></label><label>联系邮箱<input v-model="form.contactEmail" :disabled="!editable" required type="email"/></label><label class="wide">营业执照号<input v-model="form.businessLicenseNumber" :disabled="!editable" required minlength="5"/></label><label class="wide">资质文件（JPG/PNG/WebP/PDF，最多 10 份）<input :disabled="!editable" type="file" multiple accept="image/jpeg,image/png,image/webp,application/pdf" @change="addFiles(($event.target as HTMLInputElement).files)"/><small>已登记 {{form.qualificationFileIds.length}} 份。本地阶段登记私有文件元数据。</small></label><label class="wide check"><input v-model="form.agreementAccepted" :disabled="!editable" type="checkbox"/>我已阅读并同意商家入驻协议。</label><div class="wide actions"><button v-if="editable" :disabled="busy">保存草稿</button><button v-if="mine&&['DRAFT','NEEDS_CHANGES'].includes(mine.status)" type="button" class="muted" @click="applicantAction('submit')">提交审核</button><button v-if="mine&&['DRAFT','SUBMITTED','NEEDS_CHANGES'].includes(mine.status)" type="button" class="danger" @click="applicantAction('withdraw')">撤回</button></div></form><ol v-if="mine?.timeline.length" class="panel timeline"><li v-for="event in mine.timeline" :key="event.id"><b>{{labels[event.toStatus]}}</b>　{{new Date(event.createdAt).toLocaleString()}}　{{event.comment}}</li></ol></template>
</section></template>

<style scoped>.onboarding{color:var(--text)}header{display:flex;justify-content:space-between;gap:20px;margin-bottom:20px}h1,h2{margin:6px 0}p{color:var(--text-muted)}header small{color:var(--accent);letter-spacing:.15em}.panel,.notice,.card{padding:20px;border:1px solid var(--border);border-radius:9px;background:var(--surface)}.notice{margin:0 0 16px}.error{color:#e35d73}.success{color:#45ae8d}.queue{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:14px}.card{display:grid;gap:8px;text-align:left;color:var(--text)}.card em{color:var(--accent)}.panel{margin-top:16px}.form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px}label{display:grid;gap:7px;font-size:13px}.wide{grid-column:1/-1}input,textarea{padding:11px;border:1px solid var(--border);border-radius:6px;background:var(--surface-raised);color:var(--text)}.check{display:flex;flex-direction:row}.check input{width:auto}.actions{display:flex;gap:10px}button{padding:10px 16px;border:0;border-radius:6px;background:var(--accent);color:white;cursor:pointer}.muted{border:1px solid var(--border);background:var(--surface-raised);color:var(--text)}.danger{background:#983449}.timeline{display:grid;gap:9px}@media(max-width:700px){header{flex-direction:column}.form{grid-template-columns:1fr}.actions{flex-wrap:wrap}.actions button{flex:1}}</style>
