<script setup lang="ts">
import type { OrderView } from "@moecraft/shared";
definePageMeta({middleware:"auth"});useHead({meta:[{name:"robots",content:"noindex, nofollow"}]});
const route=useRoute(),api=useOrders(),order=ref<OrderView|null>(null),error=ref(""),busy=ref(false);
async function load(){try{order.value=await api.get(String(route.params.id));}catch{error.value="订单不存在或无权查看。";}}
async function cancel(){if(!order.value)return;busy.value=true;try{order.value=await api.cancel(order.value.id);}finally{busy.value=false;}}
async function confirm(){if(!order.value)return;busy.value=true;try{order.value=await api.confirmReceipt(order.value.id);}finally{busy.value=false;}}onMounted(load);
</script>
<template><div class="detail-page"><StorefrontHeader/><main><NuxtLink to="/account/orders">← 返回订单</NuxtLink><p v-if="error" class="error">{{error}}</p><p v-else-if="!order">正在加载…</p><template v-else><header><div><small>{{order.orderNumber}}</small><h1>{{order.status}}</h1></div><strong>¥{{order.payableAmount}}</strong></header><section class="panel"><h2>收货信息</h2><p>{{order.address.recipient}} · {{order.address.phone}}</p><p>{{order.address.country}} {{order.address.province}} {{order.address.city}} {{order.address.district}} {{order.address.addressLine}}</p></section><section v-for="child in order.merchantOrders" :key="child.id" class="panel"><h2>{{child.storeName}}</h2><article v-for="item in child.items" :key="item.id"><div><b>{{item.productTitle}}</b><small>{{item.skuName}} × {{item.quantity}}</small></div><strong>¥{{item.payableAmount}}</strong></article></section><section class="actions"><NuxtLink v-if="order.status==='PENDING_PAYMENT'" :to="`/payments/${order.id}`">继续支付</NuxtLink><button v-if="order.status==='PENDING_PAYMENT'" :disabled="busy" @click="cancel">取消订单</button><button v-if="order.status==='SHIPPED'" :disabled="busy" @click="confirm">确认收货</button><NuxtLink v-if="['PAID','PARTIALLY_SHIPPED','SHIPPED','COMPLETED'].includes(order.status)" :to="`/account/orders/${order.id}?afterSale=1`">申请售后</NuxtLink></section></template></main><StorefrontFooter/></div></template>
<style scoped>
:global(body){margin:0;background:#f7f4f5;color:#2e2730;font-family:Inter,"PingFang SC","Microsoft YaHei",sans-serif}.detail-page main{max-width:920px;min-height:65vh;margin:auto;padding:28px 22px 70px}.detail-page main>a{color:#7d3c5b}header{display:flex;justify-content:space-between;align-items:end;margin:26px 0}header strong{font-size:28px;color:#d44870}.panel{margin:14px 0;padding:22px;border:1px solid #eadfe4;border-radius:12px;background:white}.panel article{display:flex;justify-content:space-between;padding:12px 0;border-top:1px solid #eee}.panel article div{display:grid;gap:5px}.panel small{color:#8b7f85}.actions{display:flex;gap:10px;flex-wrap:wrap}.actions a,.actions button{padding:11px 16px;border:0;border-radius:8px;background:#7d3c5b;color:white;text-decoration:none;cursor:pointer}.actions button{background:#806f77}.error{color:#b3263e}
</style>
