<script setup lang="ts">
import type { OrderView, ShipmentTrackingView } from "@moecraft/shared";
definePageMeta({middleware:"auth"});useHead({meta:[{name:"robots",content:"noindex, nofollow"}]});
const route=useRoute(),api=useOrders(),order=ref<OrderView|null>(null),tracking=ref<ShipmentTrackingView[]>([]),error=ref(""),busy=ref(false);
const eventsOf=(shipmentId:string)=>tracking.value.find((item)=>item.id===shipmentId)?.events??[];
const itemTitle=(childId:string,orderItemId:string)=>order.value?.merchantOrders.find((child)=>child.id===childId)?.items.find((item)=>item.id===orderItemId)?.productTitle??"商品";
const fmt=(value:string)=>new Date(value).toLocaleString();
async function load(){try{order.value=await api.get(String(route.params.id));tracking.value=await api.tracking(order.value.id).catch(()=>[]);}catch{error.value="订单不存在或无权查看。";}}
async function cancel(){if(!order.value)return;busy.value=true;try{order.value=await api.cancel(order.value.id);}finally{busy.value=false;}}
async function confirm(){if(!order.value)return;busy.value=true;try{order.value=await api.confirmReceipt(order.value.id);}finally{busy.value=false;}}onMounted(load);
</script>
<template><div class="detail-page"><StorefrontHeader/><main><NuxtLink to="/account/orders">← 返回订单</NuxtLink><p v-if="error" class="error">{{error}}</p><p v-else-if="!order">正在加载…</p><template v-else><header><div><small>{{order.orderNumber}}</small><h1>{{order.status}}</h1></div><strong>¥{{order.payableAmount}}</strong></header><section class="panel"><h2>收货信息</h2><p>{{order.address.recipient}} · {{order.address.phone}}</p><p>{{order.address.country}} {{order.address.province}} {{order.address.city}} {{order.address.district}} {{order.address.addressLine}}</p></section><section v-for="child in order.merchantOrders" :key="child.id" class="panel"><h2>{{child.storeName}}<span class="child-status">{{child.status}}</span></h2><article v-for="item in child.items" :key="item.id"><div><b>{{item.productTitle}}</b><small>{{item.skuName}} × {{item.quantity}}</small></div><strong>¥{{item.payableAmount}}</strong></article><div v-for="shipment in child.shipments" :key="shipment.id" class="shipment"><header><b>{{shipment.carrierName}} · {{shipment.trackingNumber}}</b><span :class="['ship-status',shipment.status==='DELIVERED'?'done':'']">{{shipment.status==='DELIVERED'?"已签收":"运输中"}}</span></header><small class="ship-meta">发货于 {{fmt(shipment.shippedAt)}} · 内含 <template v-for="(line,index) in shipment.items" :key="line.id">{{index?"、":""}}{{itemTitle(child.id,line.orderItemId)}} × {{line.quantity}}</template></small><ol v-if="eventsOf(shipment.id).length" class="timeline"><li v-for="event in eventsOf(shipment.id)" :key="event.occurredAt+event.description"><time>{{fmt(event.occurredAt)}}</time><span>{{event.description}}</span></li></ol></div></section><section class="actions"><NuxtLink v-if="order.status==='PENDING_PAYMENT'" :to="`/payments/${order.id}`">继续支付</NuxtLink><button v-if="order.status==='PENDING_PAYMENT'" :disabled="busy" @click="cancel">取消订单</button><button v-if="order.status==='SHIPPED'" :disabled="busy" @click="confirm">确认收货</button><NuxtLink v-if="['PAID','PARTIALLY_SHIPPED','SHIPPED','COMPLETED'].includes(order.status)" :to="`/account/orders/${order.id}?afterSale=1`">申请售后</NuxtLink></section></template></main><StorefrontFooter/></div></template>
<style scoped>
:global(body){margin:0;background:#f7f4f5;color:#2e2730;font-family:Inter,"PingFang SC","Microsoft YaHei",sans-serif}.detail-page main{max-width:920px;min-height:65vh;margin:auto;padding:28px 22px 70px}.detail-page main>a{color:#7d3c5b}header{display:flex;justify-content:space-between;align-items:end;margin:26px 0}header strong{font-size:28px;color:#d44870}.panel{margin:14px 0;padding:22px;border:1px solid #eadfe4;border-radius:12px;background:white}.panel article{display:flex;justify-content:space-between;padding:12px 0;border-top:1px solid #eee}.panel article div{display:grid;gap:5px}.panel small{color:#8b7f85}.child-status{margin-left:10px;padding:3px 8px;border-radius:6px;background:#f3e7ec;color:#7d3c5b;font-size:10px;font-weight:400;vertical-align:middle}.shipment{margin-top:14px;padding:14px;border:1px solid #efe3e9;border-radius:10px;background:#fdf9fb}.shipment header{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:0;margin:0}.shipment header b{font-size:13px;color:#2e2730}.ship-status{flex:0 0 auto;padding:3px 9px;border-radius:999px;background:#fdf0e2;color:#b26a21;font-size:10px}.ship-status.done{background:#e3f3e7;color:#2c7a4b}.ship-meta{display:block;margin:6px 0 0;font-size:11px}.timeline{display:grid;gap:6px;margin:10px 0 0;padding:10px 0 0;list-style:none;border-top:1px solid #efe3e9}.timeline li{display:grid;grid-template-columns:150px minmax(0,1fr);gap:10px;font-size:11px}.timeline time{color:#a08e96}.timeline span{color:#5c4a52}.actions{display:flex;gap:10px;flex-wrap:wrap}.actions a,.actions button{padding:11px 16px;border:0;border-radius:8px;background:#7d3c5b;color:white;text-decoration:none;cursor:pointer}.actions button{background:#806f77}.error{color:#b3263e}@media(max-width:640px){.timeline li{grid-template-columns:1fr;gap:2px}}
</style>
