<script setup lang="ts">
import type { OrderStatus } from "@moecraft/shared";
definePageMeta({middleware:"auth"});useHead({meta:[{name:"robots",content:"noindex, nofollow"}]});
const state=useOrders();const labels:Record<OrderStatus,string>={PENDING_PAYMENT:"待支付",PAID:"待发货",PARTIALLY_SHIPPED:"部分发货",SHIPPED:"已发货",COMPLETED:"已完成",CANCELLED:"已取消",AFTER_SALE:"售后中",CLOSED:"已关闭"};onMounted(state.list);
</script>
<template><div class="orders-page"><StorefrontHeader/><main><header><div><p>MY ORDERS</p><h1>我的订单</h1></div><NuxtLink to="/account">账户中心</NuxtLink></header><p v-if="state.pending.value">正在加载订单…</p><p v-else-if="state.error.value" class="error">{{state.error.value}}</p><section v-else-if="!state.orders.value.length" class="empty"><h2>还没有订单</h2><NuxtLink to="/catalog">去逛逛</NuxtLink></section><section v-else class="list"><NuxtLink v-for="order in state.orders.value" :key="order.id" :to="`/account/orders/${order.id}`" class="order"><div><b>{{order.orderNumber}}</b><small>{{new Date(order.createdAt).toLocaleString()}}</small></div><div><span>{{order.storeNames.join(" / ")}}</span><small>{{order.itemCount}} 件商品</small></div><strong>¥{{order.payableAmount}}</strong><em>{{labels[order.status]}}</em></NuxtLink></section></main><StorefrontFooter/></div></template>
<style scoped>
:global(body){margin:0;background:#f7f4f5;color:#2e2730;font-family:Inter,"PingFang SC","Microsoft YaHei",sans-serif}.orders-page main{max-width:1060px;min-height:65vh;margin:auto;padding:28px 22px 70px}header{display:flex;align-items:center;justify-content:space-between}header p{color:#a65071;font-size:11px;letter-spacing:.16em}header a,.empty a{color:#7d3c5b}.list{display:grid;gap:12px}.order{display:grid;grid-template-columns:1.2fr 1fr auto auto;gap:18px;align-items:center;padding:20px;border:1px solid #eadfe4;border-radius:12px;background:#fff;color:inherit;text-decoration:none}.order div{display:grid;gap:5px}.order small{color:#8b7f85}.order strong{color:#d44870}.order em{font-style:normal}.empty{text-align:center;padding:80px}.error{color:#b3263e}@media(max-width:700px){.order{grid-template-columns:1fr auto}.order div:nth-child(2){grid-column:1/-1}}
</style>
