import type { MessageKey } from "./zh-CN";

export const enUS = {
  "nav.overview":"Overview","nav.onboarding":"Onboarding","nav.products":"Products","nav.inventory":"Inventory","nav.orders":"Orders","nav.afterSales":"After-sales","nav.members":"Team","nav.reports":"Analytics","nav.settings":"Settings",
  "header.welcome":"Welcome back","header.localTime":"Local time","header.switchLanguage":"Switch language","header.switchTheme":"Switch theme","header.logout":"Sign out",
  "role.platformAdmin":"Platform admin","role.platformOperator":"Platform operator","role.merchantOwner":"Merchant owner","role.merchantStaff":"Merchant staff","role.customer":"Applicant",
  "common.refresh":"Refresh","common.loading":"Syncing onboarding data…","common.required":"Required","common.fileCount":"{count} files","common.applicationNumber":"Application {id}","common.comingSoon":"Module in progress","common.comingSoonHint":"Navigation and access boundaries are ready. Business features will ship unit by unit.",
  "login.title":"Sign in to Console","login.subtitle":"Continue with your platform, merchant, or applicant account.","login.account":"Account","login.accountPlaceholder":"Enter username","login.password":"Password","login.passwordPlaceholder":"Enter password","login.submit":"Continue →","login.pending":"Signing in…","login.error":"Invalid credentials or console access denied.","login.security":"Session protected by encryption and access controls","login.heroTitle":"Give every passion\na stage to be seen.","login.heroSubtitle":"A brand commerce platform for figure and fan creators.",
  "onboarding.reviewerTitle":"Merchant onboarding review","onboarding.reviewerSubtitle":"Review applications, credentials, and operating status with a traceable decision history.","onboarding.applicantTitle":"Open your creator store","onboarding.applicantSubtitle":"Submit your business profile. Once approved, you can publish products and manage orders.","onboarding.pendingMetric":"Pending","onboarding.approvedMetric":"Approved",
  "onboarding.stepProfile":"Business profile","onboarding.stepReview":"Platform review","onboarding.stepOpen":"Open store","onboarding.applicationList":"Applications","onboarding.emptyList":"No applications yet","onboarding.emptyListHint":"New merchant applications will appear here.","onboarding.selectApplication":"Select an application to review","onboarding.selectApplicationHint":"All applications and their current status appear on the left.",
  "onboarding.contact":"Contact","onboarding.email":"Email","onboarding.primaryContact":"Primary business contact","onboarding.license":"License number","onboarding.manualReview":"Manual verification required","onboarding.qualifications":"Credentials","onboarding.privateStorage":"Private encrypted storage","onboarding.history":"Review history","onboarding.decision":"Decision","onboarding.reviewComment":"Review notes","onboarding.reviewPlaceholder":"Record the decision basis; required for rejection or changes","onboarding.requestChanges":"Request changes","onboarding.reject":"Reject","onboarding.approve":"✓ Approve",
  "onboarding.businessStatus":"Operating status","onboarding.active":"Active","onboarding.suspended":"Suspended","onboarding.resume":"Resume merchant","onboarding.suspend":"Suspend merchant","onboarding.statusPrefix":"Application status: {status}","onboarding.statusSubmittedHint":"Your application is in the review queue.","onboarding.statusApprovedHint":"Congratulations, your merchant access is active.","onboarding.statusEditableHint":"Complete your details and submit them for review.",
  "onboarding.profile":"Business profile","onboarding.profileHint":"Enter information that exactly matches your credentials.","onboarding.companyName":"Company / studio name","onboarding.companyPlaceholder":"e.g. Fantasy Studio","onboarding.licensePlaceholder":"Registration or license number","onboarding.contactSection":"Contact details","onboarding.contactName":"Contact name","onboarding.contactPlaceholder":"Person responsible","onboarding.phone":"Phone","onboarding.phonePlaceholder":"Used during review","onboarding.emailPlaceholder":"merchant@example.com",
  "onboarding.qualificationSection":"Credentials","onboarding.qualificationHint":"JPG, PNG, WebP, or PDF; up to 10 files.","onboarding.uploadEmpty":"Choose or drop credential files","onboarding.uploadCount":"{count} files registered","onboarding.uploadPrivateHint":"Each file is stored privately","onboarding.agreement":"I accept the MoeCraft Merchant Agreement and confirm that the information is accurate.","onboarding.saveDraft":"Save draft","onboarding.submit":"Submit for review →","onboarding.withdraw":"Withdraw",
  "onboarding.reviewDuration":"How long does review take?","onboarding.reviewDurationHint":"Complete applications are usually reviewed within 1–3 business days. Every result stays in the timeline.","onboarding.dataSafety":"Data security","onboarding.dataSafetyHint":"Credentials are private and accessible only to authorized reviewers. They are never shown in the storefront.","onboarding.progress":"Application progress",
  "onboarding.status.DRAFT":"Draft","onboarding.status.SUBMITTED":"Pending review","onboarding.status.NEEDS_CHANGES":"Changes required","onboarding.status.APPROVED":"Approved","onboarding.status.REJECTED":"Rejected","onboarding.status.WITHDRAWN":"Withdrawn",
  "onboarding.reason.blurry":"Credential file is unclear; please upload it again","onboarding.reason.mismatch":"Business information does not match the credentials","onboarding.reason.authorization":"Brand or copyright authorization is missing",
  "onboarding.event.created":"Application created","onboarding.event.submitted":"Application submitted","onboarding.event.withdrawn":"Application withdrawn",
  "onboarding.feedback.loadError":"Could not load data. Confirm that the API is running.","onboarding.feedback.fileError":"{name} has an unsupported type or size.","onboarding.feedback.saved":"Draft saved securely.","onboarding.feedback.saveError":"Could not save. Check all required fields.","onboarding.feedback.submitted":"Application submitted for platform review.","onboarding.feedback.withdrawn":"Application withdrawn.","onboarding.feedback.actionError":"Action failed. Check the application state and required data.","onboarding.feedback.reviewed":"Review result saved to the audit trail.","onboarding.feedback.reviewError":"Review failed. Notes are required for rejection or requested changes.","onboarding.feedback.resumed":"Merchant resumed.","onboarding.feedback.suspended":"Merchant suspended.","onboarding.feedback.statusError":"Could not update merchant status.","onboarding.feedback.statusReason":"Platform operating-status update"
} satisfies Record<MessageKey, string>;
