export type ApiRow = { name:string; type:string; defaultValue:string; description:string };
export type ComponentDoc = { group:string; name:string; description:string; usage:string; props:ApiRow[]; slots:ApiRow[]; events:ApiRow[] };
const row=(name:string,type:string,defaultValue:string,description:string):ApiRow=>({name,type,defaultValue,description});
export const componentDocs:ComponentDoc[]=[
 {group:"基础",name:"UiButton",description:"统一按钮层级、尺寸、加载和禁用状态。",usage:'<UiButton variant="primary" :loading="saving">保存</UiButton>',props:[row("variant","primary | secondary | danger | ghost","primary","视觉层级"),row("size","sm | md | lg","md","按钮尺寸"),row("loading","boolean","false","加载并禁用"),row("disabled","boolean","false","禁用交互"),row("type","button | submit | reset","button","原生类型")],slots:[row("default","VNode","—","按钮内容")],events:[row("click","MouseEvent","—","点击事件")]},
 {group:"基础",name:"UiBadge",description:"展示状态、类别和轻量标签。",usage:'<UiBadge tone="success">营业中</UiBadge>',props:[row("tone","neutral | accent | success | warning | danger","neutral","语义色彩")],slots:[row("default","VNode","—","标签内容")],events:[]},
 {group:"数据录入",name:"UiInput",description:"支持 v-model、原生 input 属性和错误状态。",usage:'<UiInput v-model="form.name" :invalid="!!errors.name" />',props:[row("modelValue","string | number","—","输入值"),row("invalid","boolean","false","错误状态"),row("…attrs","InputHTMLAttributes","—","原生属性透传")],slots:[],events:[row("update:modelValue","string","—","输入值变化")]},
 {group:"数据录入",name:"UiTextarea",description:"统一多行文本输入。",usage:'<UiTextarea v-model="form.description" :rows="4" />',props:[row("modelValue","string","—","文本内容"),row("invalid","boolean","false","错误状态"),row("…attrs","TextareaHTMLAttributes","—","原生属性透传")],slots:[],events:[row("update:modelValue","string","—","内容变化")]},
 {group:"数据录入",name:"UiSelect",description:"统一下拉选择器并透传原生属性。",usage:'<UiSelect v-model="status"><option value="OPEN">营业中</option></UiSelect>',props:[row("modelValue","string | number","—","选中值"),row("…attrs","SelectHTMLAttributes","—","原生属性透传")],slots:[row("default","option | optgroup","—","选项内容")],events:[row("update:modelValue","string","—","选项变化")]},
 {group:"数据录入",name:"UiField",description:"统一标签、必填、提示与错误信息。",usage:'<UiField label="客服邮箱" required><UiInput v-model="email" /></UiField>',props:[row("label","string","—","字段标签"),row("hint","string","—","帮助文本"),row("error","string","—","错误文本"),row("required","boolean","false","必填标识")],slots:[row("default","VNode","—","表单控件")],events:[]},
 {group:"容器",name:"UiCard",description:"包含标题、操作区、主体与页脚的内容容器。",usage:'<UiCard title="店铺资料"><template #actions>...</template></UiCard>',props:[row("title","string","—","标题"),row("subtitle","string","—","副标题"),row("padding","none | sm | md | lg","md","内部留白"),row("interactive","boolean","false","悬浮反馈")],slots:[row("default","VNode","—","主体"),row("header","VNode","—","自定义头部"),row("actions","VNode","—","操作区"),row("footer","VNode","—","页脚")],events:[]},
 {group:"数据展示",name:"UiList",description:"泛型列表和作用域插槽。",usage:'<UiList :items="members"><template #default="{ item }">{{ item.name }}</template></UiList>',props:[row("items","T[]","—","列表数据"),row("keyBy","(item,index) => Key","index","key 生成函数")],slots:[row("default","{ item, index }","—","列表项目")],events:[]},
 {group:"数据展示",name:"UiTable",description:"配置式表格，支持自定义单元格。",usage:'<UiTable :columns="columns" :rows="members"><template #cell-role="{ value }">...</template></UiTable>',props:[row("columns","UiTableColumn[]","—","列定义"),row("rows","Record<string,unknown>[]","—","行数据"),row("rowKey","string","id","唯一键字段"),row("emptyText","string","—","空提示")],slots:[row("cell-{key}","{ row, value }","—","列单元格")],events:[]},
 {group:"反馈",name:"UiEmptyState",description:"无数据、无结果和首次使用状态。",usage:'<UiEmptyState title="暂无成员" description="邀请后显示" />',props:[row("title","string","—","标题"),row("description","string","—","说明"),row("icon","string","◇","字符图标")],slots:[row("default","VNode","—","操作内容")],events:[]},
 {group:"布局",name:"UiPageContainer",description:"控制页面宽度、边距与滚动。",usage:'<UiPageContainer size="lg">...</UiPageContainer>',props:[row("size","md | lg | full","lg","960 / 1280 / 无限制")],slots:[row("default","VNode","—","页面内容")],events:[]},
 {group:"布局",name:"UiPageHeader",description:"标准页面眉题、标题、说明和操作区。",usage:'<UiPageHeader eyebrow="STORE" title="店铺管理"><template #actions>...</template></UiPageHeader>',props:[row("eyebrow","string","—","分类文字"),row("title","string","—","主标题"),row("description","string","—","页面说明")],slots:[row("actions","VNode","—","页面操作区")],events:[]},
 {group:"布局",name:"UiSplitLayout",description:"主栏与侧栏响应式分栏。",usage:'<UiSplitLayout aside-width="360px"><main/><template #aside>...</template></UiSplitLayout>',props:[row("asideWidth","string","360px","侧栏宽度"),row("gap","string","20px","栏间距")],slots:[row("default","VNode","—","主栏"),row("aside","VNode","—","侧栏")],events:[]}
];
export const tokens=[["Accent","#5d50df","--accent"],["Accent soft","#eceaff","--accent-soft"],["Success","#16866c","--success"],["Danger","#c94360","--danger"],["Surface","#ffffff","--surface"],["Background","#f5f6fb","--bg"],["Text","#20243a","--text"],["Border","#e0e4ee","--border"]] as const;
