<script setup lang="ts">
import { onMounted } from "vue";
import { UiButton,UiPageContainer,UiPageHeader,UiTable,type UiTableColumn } from "@moecraft/ui";
import type { AdminButtonPermission } from "@moecraft/shared";
import ProductDraftDrawer from "./components/ProductDraftDrawer.vue";
import { useProductManagement } from "./composables/useProductManagement";
const props=withDefaults(defineProps<{buttonPermissions?:AdminButtonPermission[]}>(),{buttonPermissions:()=>[]});
const state=useProductManagement();
const columns:UiTableColumn[]=[{key:"product",label:"商品",width:"29%"},{key:"status",label:"状态",width:"11%"},{key:"sku",label:"SKU / 库存",width:"14%"},{key:"price",label:"价格区间",width:"14%"},{key:"updated",label:"更新时间",width:"13%"},{key:"actions",label:"操作",width:"19%",align:"right"}];
const canManage=()=>props.buttonPermissions.includes("products.manage");const canSubmit=()=>props.buttonPermissions.includes("products.submit");
function money(value?:number){return value===undefined?"—":new Intl.NumberFormat("zh-CN",{style:"currency",currency:"CNY"}).format(value/100);}
onMounted(state.load);
</script>
<template><UiPageContainer size="full" class="product-page content-scroll"><UiPageHeader eyebrow="PRODUCT STUDIO" title="商品管理" description="维护商品草稿、审核状态、SKU 与上架生命周期。"><template #actions><UiButton v-if="canManage()" @click="state.create">＋ 新建商品草稿</UiButton></template></UiPageHeader><p v-if="state.error.value" class="error">{{state.error.value}}</p><section class="panel"><div class="filters"><input v-model="state.keyword.value" placeholder="搜索商品名称"><select v-model="state.status.value"><option value="ALL">全部状态</option><option value="DRAFT">草稿</option><option value="PENDING_REVIEW">待审核</option><option value="APPROVED">已通过</option><option value="REJECTED">已驳回</option><option value="ACTIVE">在售</option><option value="INACTIVE">已下架</option></select></div><div v-if="state.loading.value" class="loading">正在加载商品…</div><UiTable v-else :columns="columns" :rows="state.filtered.value.map(item=>({...item,product:item.titleZhCn,sku:item.skuCount,price:item.priceMin,updated:item.updatedAt,actions:item.id}))" empty-text="暂无商品"><template #cell-product="{row}"><div class="name"><b>{{row.titleZhCn}}</b><small>{{row.titleEnUs||row.categoryName||'资料待完善'}}</small></div></template><template #cell-status="{row}"><em :class="String(row.status).toLowerCase()">{{row.status}}</em></template><template #cell-sku="{row}">{{row.skuCount}} 个 / {{row.stock}} 件</template><template #cell-price="{row}">{{money(row.priceMin as number|undefined)}}<span v-if="row.priceMax!==row.priceMin"> – {{money(row.priceMax as number|undefined)}}</span></template><template #cell-updated="{row}">{{new Date(row.updatedAt as string).toLocaleString()}}</template><template #cell-actions="{row}"><div class="actions"><UiButton size="sm" variant="ghost" @click="state.edit(row.id as string)">查看/编辑</UiButton><UiButton v-if="canSubmit()&&['DRAFT','REJECTED'].includes(row.status as string)" size="sm" @click="state.action(row.id as string,'submit')">提交审核</UiButton><UiButton v-if="canManage()&&['APPROVED','INACTIVE'].includes(row.status as string)" size="sm" @click="state.action(row.id as string,'publish')">上架</UiButton><UiButton v-if="canManage()&&row.status==='ACTIVE'" size="sm" variant="secondary" @click="state.action(row.id as string,'unpublish')">下架</UiButton><UiButton v-if="canManage()" size="sm" variant="secondary" @click="state.action(row.id as string,'copy')">复制</UiButton><UiButton v-if="canManage()&&['DRAFT','REJECTED','INACTIVE'].includes(row.status as string)" size="sm" variant="danger" @click="state.archive(row.id as string)">归档</UiButton></div></template></UiTable></section><Teleport to="body"><ProductDraftDrawer v-if="state.drawerOpen.value" :model-value="state.form" :catalog="state.catalog.value" :review-events="state.reviewEvents.value" :editing="Boolean(state.editingId.value)" :editable="state.editable.value" :busy="state.busy.value" @save="state.save" @close="state.drawerOpen.value=false"/></Teleport></UiPageContainer></template>
<style scoped lang="less">.product-page{background:var(--app-bg)}.panel{padding:20px;border:1px solid var(--border);border-radius:18px;background:var(--surface);box-shadow:var(--shadow)}.filters{display:flex;gap:10px;margin-bottom:16px}.filters input{flex:1}.filters input,.filters select{padding:11px;border:1px solid var(--border);border-radius:9px;background:var(--surface-raised);color:var(--text)}.name{display:grid}.name b{color:var(--text)}.name small{margin-top:3px;color:var(--text-muted)}em{padding:5px 8px;border-radius:99px;background:var(--accent-soft);color:var(--accent);font-size:9px;font-style:normal}.rejected{background:#ffe4eb;color:#c43d5c}.active{background:#dff7ef;color:#128562}.actions{display:flex;flex-wrap:wrap;justify-content:flex-end;gap:5px}.error{padding:12px;border-radius:10px;background:#ffe4eb;color:#be3c59}.loading{padding:50px;text-align:center}@media(max-width:650px){.filters{flex-direction:column}}</style>
