export const CATALOG_ENTITY_TYPES = ["categories", "brands", "franchises", "characters", "tags", "attribute-templates"] as const;
export type CatalogEntityType = (typeof CATALOG_ENTITY_TYPES)[number];

export type CatalogTranslation = { nameZhCn: string; nameEnUs: string | null };
export type CatalogBaseView = CatalogTranslation & {
  id: string;
  slug: string;
  isActive: boolean;
  sortOrder: number;
  productCount: number;
  createdAt: string;
  updatedAt: string;
};
export type CategoryView = CatalogBaseView & { parentId: string | null; descriptionZhCn: string | null; descriptionEnUs: string | null; children?: CategoryView[] };
export type BrandView = CatalogBaseView & { descriptionZhCn: string | null; descriptionEnUs: string | null };
export type FranchiseView = BrandView & { characterCount: number };
export type CharacterView = CatalogBaseView & { franchiseId: string; franchiseName: string };
export type TagView = CatalogBaseView;
export type AttributeTemplateView = Omit<CatalogBaseView, "slug" | "productCount"> & { code: string; categoryId: string | null; inputType: "TEXT" | "NUMBER" | "SELECT" | "MULTI_SELECT" | "BOOLEAN"; options: string[]; isRequired: boolean };
export type CatalogProductSort = "RELEVANCE" | "NEWEST" | "PRICE_ASC" | "PRICE_DESC" | "SALES";
export type PublicProductCard = {
  id: string;
  titleZhCn: string;
  titleEnUs: string | null;
  storeName: string;
  storeSlug: string;
  categoryName: string | null;
  categorySlug: string | null;
  brandName: string | null;
  brandSlug: string | null;
  franchiseName: string | null;
  franchiseSlug: string | null;
  priceAmount: number | null;
  currency: string;
  available: number;
  inStock: boolean;
  saleType: "IN_STOCK" | "PREORDER";
  coverFileId: string | null;
  coverAlt: string | null;
  salesCount: number;
  updatedAt: string;
};
export type PublicProductSearchResult = { items: PublicProductCard[]; total: number; page: number; pageSize: number; totalPages: number };
export type PublicProductMedia = { id: string; fileId: string; kind: "IMAGE" | "VIDEO"; altZhCn: string | null; altEnUs: string | null; isCover: boolean };
export type PublicProductSku = { id: string; code: string; nameZhCn: string; nameEnUs: string | null; optionValues: Record<string, string>; priceAmount: number; currency: string; available: number; inStock: boolean };
export type PublicStoreSummary = { id: string; name: string; slug: string; logoFileId: string | null; description: string | null; customerServiceEmail: string | null; customerServicePhone: string | null };
export type PublicProductDetail = {
  id: string;
  titleZhCn: string;
  titleEnUs: string | null;
  descriptionZhCn: string | null;
  descriptionEnUs: string | null;
  material: string | null;
  scale: string | null;
  manufacturer: string | null;
  copyrightNotice: string | null;
  saleType: "IN_STOCK" | "PREORDER";
  presaleNotice: string | null;
  shippingWindowStart: string | null;
  shippingWindowEnd: string | null;
  afterSalesSummary: string | null;
  category: Pick<CategoryView, "id" | "slug" | "nameZhCn" | "nameEnUs"> | null;
  brand: Pick<BrandView, "id" | "slug" | "nameZhCn" | "nameEnUs"> | null;
  franchise: Pick<FranchiseView, "id" | "slug" | "nameZhCn" | "nameEnUs"> | null;
  character: Pick<CharacterView, "id" | "slug" | "nameZhCn" | "nameEnUs"> | null;
  tags: Array<Pick<TagView, "id" | "slug" | "nameZhCn" | "nameEnUs">>;
  store: PublicStoreSummary;
  media: PublicProductMedia[];
  skus: PublicProductSku[];
  salesCount: number;
  createdAt: string;
  updatedAt: string;
};
export type CatalogOverview = { categories: CategoryView[]; brands: BrandView[]; franchises: FranchiseView[]; characters: CharacterView[]; tags: TagView[]; attributeTemplates: AttributeTemplateView[]; products: PublicProductCard[] };
