<script setup lang="ts">
import { computed, onBeforeUnmount, ref } from "vue";
import type { MessageKey, Locale } from "../../i18n";
import { useLocale } from "../../i18n";
import type { UserRole } from "@moecraft/shared";

const props = defineProps<{ activePage: string; theme: "system" | "light" | "dark"; user: { displayName: string; username: string; roles: UserRole[] } | null }>();
defineEmits<{ toggleTheme: []; toggleLocale: []; logout: [] }>();
const { locale, t } = useLocale();
const now = ref(new Date());
const timer = window.setInterval(() => { now.value = new Date(); }, 1000);
onBeforeUnmount(() => window.clearInterval(timer));
const pageKey = computed(() => props.activePage in pageKeys ? pageKeys[props.activePage] : "nav.overview");
const pageKeys: Record<string, MessageKey> = { overview:"nav.overview",onboarding:"nav.onboarding",products:"nav.products",inventory:"nav.inventory",orders:"nav.orders",afterSales:"nav.afterSales",members:"nav.members",reports:"nav.reports",settings:"nav.settings" };
const time = computed(() => new Intl.DateTimeFormat(locale.value, { hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false }).format(now.value));
const date = computed(() => new Intl.DateTimeFormat(locale.value, { month:"short",day:"numeric",weekday:"short" }).format(now.value));
const role = computed(() => { const value = props.user?.roles[0] ?? "CUSTOMER"; const keys: Record<UserRole,MessageKey>={PLATFORM_ADMIN:"role.platformAdmin",PLATFORM_OPERATOR:"role.platformOperator",MERCHANT_OWNER:"role.merchantOwner",MERCHANT_STAFF:"role.merchantStaff",CUSTOMER:"role.customer"}; return t(keys[value]); });
const initials = computed(() => (props.user?.displayName || props.user?.username || "M").slice(0, 1).toUpperCase());
</script>
<template><header class="header"><div class="page-title"><span>{{t('header.welcome')}}，{{user?.displayName||user?.username||'MoeCraft'}}</span><h2>{{t(pageKey)}}</h2></div><div class="header-actions"><div class="clock" :title="t('header.localTime')"><i>◷</i><div><b>{{time}}</b><small>{{date}}</small></div></div><button class="tool-button language" :aria-label="t('header.switchLanguage')" @click="$emit('toggleLocale')"><span>{{locale==='zh-CN'?'中':'EN'}}</span>{{locale==='zh-CN'?'中文':'English'}}</button><button class="tool-button theme" :aria-label="t('header.switchTheme')" @click="$emit('toggleTheme')">{{theme==='dark'?'☾':theme==='light'?'☀':'◐'}}</button><div class="divider"/><div class="profile"><span class="avatar">{{initials}}<i/></span><div><b>{{user?.displayName||user?.username||'MoeCraft'}}</b><small>{{role}}</small></div></div><button class="logout" :title="t('header.logout')" @click="$emit('logout')">↪</button></div></header></template>
<style scoped>.header{position:relative;z-index:10;display:flex;min-height:74px;align-items:center;justify-content:space-between;gap:20px;padding:0 clamp(18px,2.5vw,34px);border-bottom:1px solid var(--border);background:color-mix(in srgb,var(--surface) 94%,transparent);box-shadow:0 5px 18px rgb(36 42 74 / 5%);backdrop-filter:blur(14px)}.page-title span{color:var(--text-muted);font-size:10px}.page-title h2{margin:3px 0 0;color:var(--text);font-size:17px}.header-actions{display:flex;align-items:center;gap:9px}.clock{display:flex;align-items:center;gap:9px;padding-right:10px}.clock i{color:#6957e8;font-size:18px;font-style:normal}.clock div,.profile div{display:grid}.clock b{color:var(--text);font-size:12px;font-variant-numeric:tabular-nums}.clock small,.profile small{color:var(--text-muted);font-size:9px}.tool-button,.logout{height:36px;border:1px solid var(--border);border-radius:9px;background:var(--surface-raised);color:var(--text-secondary);cursor:pointer}.tool-button:hover,.logout:hover{border-color:#6957e8;color:#6957e8}.language{display:flex;align-items:center;gap:7px;padding:0 11px;font-size:10px}.language span{display:grid;width:20px;height:20px;place-items:center;border-radius:6px;background:#6957e8;color:white;font-size:9px}.theme{width:36px;font-size:16px}.divider{width:1px;height:30px;margin:0 3px;background:var(--border)}.profile{display:flex;align-items:center;gap:9px}.profile b{max-width:130px;overflow:hidden;color:var(--text);font-size:11px;text-overflow:ellipsis;white-space:nowrap}.avatar{position:relative;display:grid;width:36px;height:36px;place-items:center;border-radius:11px;background:linear-gradient(145deg,#6957e8,#a76fd9);color:white;font-size:13px;font-weight:700}.avatar i{position:absolute;width:8px;height:8px;right:-1px;bottom:-1px;border:2px solid var(--surface);border-radius:50%;background:#27a979}.logout{width:34px;border:0;background:transparent;font-size:17px}@media(max-width:930px){.clock{display:none}.header{padding:0 17px}}@media(max-width:620px){.page-title span,.language{display:none}.profile div,.divider{display:none}.header-actions{gap:4px}}
</style>
