import { BadRequestException, ConflictException, ForbiddenException, Injectable, NotFoundException } from "@nestjs/common";
import type { ProductDraftListItem, ProductDraftView } from "@moecraft/shared";
import { Prisma } from "@prisma/client";
import { randomUUID } from "node:crypto";
import { PrismaService } from "../prisma/prisma.service";
import type { SaveProductDraftDto } from "./product.dto";

@Injectable()
export class ProductService {
  constructor(private readonly prisma: PrismaService) {}

  async list(userId: string): Promise<ProductDraftListItem[]> {
    const store = await this.store(userId);
    const products = await this.prisma.product.findMany({ where: { storeId: store.id, status: { not: "ARCHIVED" } }, include: { category: true, skus: { include: { inventory: true } }, media: { orderBy: { sortOrder: "asc" } } }, orderBy: { updatedAt: "desc" } });
    return products.map((item) => { const prices = item.skus.map((sku) => sku.priceAmount); return { id:item.id,titleZhCn:item.titleZhCn,titleEnUs:item.titleEnUs??undefined,status:item.status,categoryName:item.category?.nameZhCn,skuCount:item.skus.length,priceMin:prices.length?Math.min(...prices):undefined,priceMax:prices.length?Math.max(...prices):undefined,stock:item.skus.reduce((sum,sku)=>sum+(sku.inventory?.onHand??0),0),coverFileId:item.media.find(media=>media.isCover)?.fileId,updatedAt:item.updatedAt.toISOString() }; });
  }

  async detail(userId:string,id:string):Promise<ProductDraftView>{ const store=await this.store(userId);const item=await this.prisma.product.findFirst({where:{id,storeId:store.id},include:{tags:true,skus:{include:{inventory:true},orderBy:{createdAt:"asc"}},media:{orderBy:{sortOrder:"asc"}}}});if(!item)throw new NotFoundException("PRODUCT_NOT_FOUND");return this.view(item); }
  async create(userId:string,dto:SaveProductDraftDto){const store=await this.store(userId);await this.validate(userId,dto);try{return await this.prisma.$transaction(async(tx)=>{const item=await tx.product.create({data:{...this.productData(dto),storeId:store.id,tags:{connect:dto.tagIds.map(id=>({id}))},skus:{create:dto.skus.map(sku=>({...this.skuData(sku),inventory:{create:{onHand:sku.initialStock}}}))},media:{create:dto.media.map(media=>this.mediaData(media))}}});await tx.auditLog.create({data:{actorId:userId,action:"product.draft.created",targetType:"Product",targetId:item.id}});return this.detailTx(tx,store.id,item.id);});}catch(error){this.rethrow(error);}}
  async update(userId:string,id:string,dto:SaveProductDraftDto){const store=await this.store(userId);const current=await this.prisma.product.findFirst({where:{id,storeId:store.id}});if(!current)throw new NotFoundException("PRODUCT_NOT_FOUND");if(!["DRAFT","REJECTED"].includes(current.status))throw new BadRequestException("PRODUCT_STATUS_NOT_EDITABLE");await this.validate(userId,dto);try{return await this.prisma.$transaction(async(tx)=>{await tx.inventory.deleteMany({where:{sku:{productId:id}}});await tx.sku.deleteMany({where:{productId:id}});await tx.productMedia.deleteMany({where:{productId:id}});await tx.product.update({where:{id},data:{...this.productData(dto),tags:{set:dto.tagIds.map(tagId=>({id:tagId}))},skus:{create:dto.skus.map(sku=>({...this.skuData(sku),inventory:{create:{onHand:sku.initialStock}}}))},media:{create:dto.media.map(media=>this.mediaData(media))}}});await tx.auditLog.create({data:{actorId:userId,action:"product.draft.updated",targetType:"Product",targetId:id}});return this.detailTx(tx,store.id,id);});}catch(error){this.rethrow(error);}}
  async archive(userId:string,id:string){const store=await this.store(userId);const result=await this.prisma.product.updateMany({where:{id,storeId:store.id,status:{in:["DRAFT","REJECTED","INACTIVE"]}},data:{status:"ARCHIVED"}});if(!result.count)throw new BadRequestException("PRODUCT_CANNOT_BE_ARCHIVED");await this.prisma.auditLog.create({data:{actorId:userId,action:"product.archived",targetType:"Product",targetId:id}});return {archived:true};}

  private productData(dto:SaveProductDraftDto){return{titleZhCn:dto.titleZhCn,titleEnUs:dto.titleEnUs||null,descriptionZhCn:dto.descriptionZhCn||null,descriptionEnUs:dto.descriptionEnUs||null,categoryId:dto.categoryId||null,brandId:dto.brandId||null,franchiseId:dto.franchiseId||null,characterId:dto.characterId||null,material:dto.material||null,scale:dto.scale||null,manufacturer:dto.manufacturer||null,copyrightNotice:dto.copyrightNotice||null};}
  private skuData(sku:SaveProductDraftDto["skus"][number]){return{code:sku.code?.trim()||`MC-${randomUUID().slice(0,8).toUpperCase()}`,nameZhCn:sku.nameZhCn,nameEnUs:sku.nameEnUs||null,barcode:sku.barcode||null,optionValues:sku.optionValues as Prisma.InputJsonValue,weightGrams:sku.weightGrams??null,lengthMm:sku.lengthMm??null,widthMm:sku.widthMm??null,heightMm:sku.heightMm??null,priceAmount:sku.priceAmount,currency:(sku.currency||"CNY").toUpperCase()};}
  private mediaData(media:SaveProductDraftDto["media"][number]){return{fileId:media.fileId,kind:media.kind,altZhCn:media.altZhCn||null,altEnUs:media.altEnUs||null,sortOrder:media.sortOrder,isCover:media.isCover};}
  private async validate(userId:string,dto:SaveProductDraftDto){if(dto.media.filter(item=>item.isCover).length>1)throw new BadRequestException("PRODUCT_MEDIA_MULTIPLE_COVERS");const customCodes=dto.skus.map(item=>item.code?.trim()).filter((code):code is string=>Boolean(code));if(new Set(customCodes).size!==customCodes.length)throw new BadRequestException("DUPLICATE_SKU_CODE");const [category,brand,franchise,character,tags]=await Promise.all([dto.categoryId?this.prisma.category.count({where:{id:dto.categoryId,isActive:true}}):1,dto.brandId?this.prisma.brand.count({where:{id:dto.brandId,isActive:true}}):1,dto.franchiseId?this.prisma.franchise.count({where:{id:dto.franchiseId,isActive:true}}):1,dto.characterId?this.prisma.character.count({where:{id:dto.characterId,isActive:true,...(dto.franchiseId?{franchiseId:dto.franchiseId}:{})}}):1,this.prisma.tag.count({where:{id:{in:dto.tagIds},isActive:true}})]);if(!category||!brand||!franchise||!character||tags!==dto.tagIds.length)throw new BadRequestException("INVALID_PRODUCT_CATALOG_REFERENCE");if(dto.media.length){const count=await this.prisma.fileAsset.count({where:{id:{in:dto.media.map(item=>item.fileId)},ownerId:userId,purpose:"product-media",status:"READY"}});if(count!==dto.media.length)throw new BadRequestException("INVALID_PRODUCT_MEDIA");}}
  private async store(userId:string){const member=await this.prisma.merchantMember.findFirst({where:{userId},include:{merchant:{include:{store:true}}}});if(!member?.merchant.store||member.merchant.status!=="ACTIVE")throw new ForbiddenException("ACTIVE_MERCHANT_STORE_REQUIRED");return member.merchant.store;}
  private async detailTx(tx:Prisma.TransactionClient,storeId:string,id:string){const item=await tx.product.findFirstOrThrow({where:{id,storeId},include:{tags:true,skus:{include:{inventory:true},orderBy:{createdAt:"asc"}},media:{orderBy:{sortOrder:"asc"}}}});return this.view(item);}
  private view(item:ProductRecord):ProductDraftView{return{id:item.id,storeId:item.storeId,status:item.status,titleZhCn:item.titleZhCn,titleEnUs:item.titleEnUs??undefined,descriptionZhCn:item.descriptionZhCn??undefined,descriptionEnUs:item.descriptionEnUs??undefined,categoryId:item.categoryId??undefined,brandId:item.brandId??undefined,franchiseId:item.franchiseId??undefined,characterId:item.characterId??undefined,tagIds:item.tags.map(tag=>tag.id),material:item.material??undefined,scale:item.scale??undefined,manufacturer:item.manufacturer??undefined,copyrightNotice:item.copyrightNotice??undefined,skus:item.skus.map(sku=>({id:sku.id,code:sku.code,nameZhCn:sku.nameZhCn,nameEnUs:sku.nameEnUs??undefined,barcode:sku.barcode??undefined,optionValues:(sku.optionValues as Record<string,string>|null)??{},weightGrams:sku.weightGrams??undefined,lengthMm:sku.lengthMm??undefined,widthMm:sku.widthMm??undefined,heightMm:sku.heightMm??undefined,priceAmount:sku.priceAmount,currency:sku.currency,initialStock:sku.inventory?.onHand??0})),media:item.media.map(media=>({id:media.id,fileId:media.fileId,kind:media.kind as "IMAGE"|"VIDEO",altZhCn:media.altZhCn??undefined,altEnUs:media.altEnUs??undefined,sortOrder:media.sortOrder,isCover:media.isCover})),createdAt:item.createdAt.toISOString(),updatedAt:item.updatedAt.toISOString()};}
  private rethrow(error:unknown):never{if(error instanceof Prisma.PrismaClientKnownRequestError&&error.code==="P2002")throw new ConflictException("SKU_CODE_ALREADY_USED");throw error;}
}

type ProductRecord=Prisma.ProductGetPayload<{include:{tags:true;skus:{include:{inventory:true}};media:true}}>;
