import { BadRequestException, ConflictException, ForbiddenException, Injectable, NotFoundException } from "@nestjs/common";
import type { ProductDraftListItem, ProductDraftView, ProductReviewDetail, ProductStatus } from "@moecraft/shared";
import { Prisma } from "@prisma/client";
import { randomUUID } from "node:crypto";
import { PrismaService } from "../prisma/prisma.service";
import type { SaveProductDraftDto } from "./product.dto";
import { canTransitionProduct } from "./product-workflow";

@Injectable()
export class ProductService {
  constructor(private readonly prisma: PrismaService) {}

  async list(userId: string): Promise<ProductDraftListItem[]> {
    const store = await this.store(userId);
    const products = await this.prisma.product.findMany({ where: { storeId: store.id, status: { not: "ARCHIVED" } }, include: { category: true, skus: { where: { isActive: true }, include: { inventory: true } }, media: { orderBy: { sortOrder: "asc" } } }, orderBy: { updatedAt: "desc" } });
    return products.map((item) => { const prices = item.skus.map((sku) => sku.priceAmount); return { id:item.id,titleZhCn:item.titleZhCn,titleEnUs:item.titleEnUs??undefined,status:item.status,categoryName:item.category?.nameZhCn,skuCount:item.skus.length,priceMin:prices.length?Math.min(...prices):undefined,priceMax:prices.length?Math.max(...prices):undefined,stock:item.skus.reduce((sum,sku)=>sum+(sku.inventory?.onHand??0),0),coverFileId:item.media.find(media=>media.isCover)?.fileId,updatedAt:item.updatedAt.toISOString() }; });
  }

  async detail(userId:string,id:string):Promise<ProductReviewDetail>{const store=await this.store(userId);const item=await this.prisma.product.findFirst({where:{id,storeId:store.id},include:{tags:true,skus:{where:{isActive:true},include:{inventory:true},orderBy:{createdAt:"asc"}},media:{orderBy:{sortOrder:"asc"}},reviewEvents:{orderBy:{createdAt:"desc"}}}});if(!item)throw new NotFoundException("PRODUCT_NOT_FOUND");return{...this.view(item),storeName:store.name,reviewEvents:item.reviewEvents.map(event=>this.reviewEventView(event))};}
  async create(userId:string,dto:SaveProductDraftDto){const store=await this.store(userId);await this.validate(store.merchantId,dto);try{return await this.prisma.$transaction(async(tx)=>{const item=await tx.product.create({data:{...this.productData(dto),storeId:store.id,tags:{connect:dto.tagIds.map(id=>({id}))},skus:{create:dto.skus.map(sku=>({...this.skuData(sku),inventory:{create:{onHand:sku.initialStock}}}))},media:{create:dto.media.map(media=>this.mediaData(media))}}});const inventories=await tx.inventory.findMany({where:{sku:{productId:item.id}}});if(inventories.length)await tx.inventoryLedgerEntry.createMany({data:inventories.map(inventory=>({inventoryId:inventory.id,type:"INITIAL_STOCK" as const,onHandDelta:inventory.onHand,reservedDelta:0,onHandAfter:inventory.onHand,reservedAfter:0,reason:"商品草稿初始库存",actorId:userId}))});await tx.auditLog.create({data:{actorId:userId,action:"product.draft.created",targetType:"Product",targetId:item.id}});return this.detailTx(tx,store.id,item.id);});}catch(error){this.rethrow(error);}}
  async update(userId:string,id:string,dto:SaveProductDraftDto){
    const store=await this.store(userId);const current=await this.prisma.product.findFirst({where:{id,storeId:store.id}});
    if(!current)throw new NotFoundException("PRODUCT_NOT_FOUND");
    if(!["DRAFT","REJECTED","APPROVED","INACTIVE"].includes(current.status))throw new BadRequestException("PRODUCT_STATUS_NOT_EDITABLE");
    await this.validate(userId,dto);const resetsReview=["APPROVED","INACTIVE"].includes(current.status);
    try{return await this.prisma.$transaction(async(tx)=>{
      const existing=await tx.sku.findMany({where:{productId:id},include:{inventory:true}});
      const existingById=new Map(existing.map(sku=>[sku.id,sku]));
      const requestedIds=new Set(dto.skus.map(sku=>sku.id).filter((skuId):skuId is string=>Boolean(skuId)));
      if([...requestedIds].some(skuId=>!existingById.has(skuId)))throw new BadRequestException("INVALID_PRODUCT_SKU");
      for(const sku of dto.skus){
        if(sku.id){
          const previous=existingById.get(sku.id)!;
          if(!previous.inventory)throw new BadRequestException("INVENTORY_NOT_FOUND");
          const delta=sku.initialStock-previous.inventory.onHand;
          if(previous.inventory.onHand+delta<previous.inventory.reserved)throw new BadRequestException("INSUFFICIENT_AVAILABLE_STOCK");
          await tx.sku.update({where:{id:sku.id},data:{...this.skuData(sku),isActive:true}});
          if(delta!==0){const nextOnHand=previous.inventory.onHand+delta;const changed=await tx.inventory.updateMany({where:{id:previous.inventory.id,version:previous.inventory.version,onHand:previous.inventory.onHand,reserved:previous.inventory.reserved},data:{onHand:nextOnHand,version:{increment:1}}});if(!changed.count)throw new ConflictException("INVENTORY_VERSION_CHANGED");await tx.inventoryLedgerEntry.create({data:{inventoryId:previous.inventory.id,type:"ADJUSTMENT",onHandDelta:delta,reservedDelta:0,onHandAfter:nextOnHand,reservedAfter:previous.inventory.reserved,reason:"商品草稿保存时调整库存",actorId:userId}});}
        }else{
          const created=await tx.sku.create({data:{...this.skuData(sku),productId:id,inventory:{create:{onHand:sku.initialStock}}},include:{inventory:true}});
          if(!created.inventory)throw new BadRequestException("INVENTORY_NOT_FOUND");
          await tx.inventoryLedgerEntry.create({data:{inventoryId:created.inventory.id,type:"INITIAL_STOCK",onHandDelta:sku.initialStock,reservedDelta:0,onHandAfter:sku.initialStock,reservedAfter:0,reason:"新增 SKU 初始库存",actorId:userId}});
        }
      }
      const removed=existing.filter(sku=>sku.isActive&&!requestedIds.has(sku.id));
      if(removed.some(sku=>(sku.inventory?.reserved??0)>0))throw new BadRequestException("RESERVED_SKU_CANNOT_BE_REMOVED");
      if(removed.length)await tx.sku.updateMany({where:{id:{in:removed.map(sku=>sku.id)}},data:{isActive:false}});
      await tx.productMedia.deleteMany({where:{productId:id}});
      await tx.product.update({where:{id},data:{...this.productData(dto),...(resetsReview?{status:"DRAFT" as const}:{}),tags:{set:dto.tagIds.map(tagId=>({id:tagId}))},media:{create:dto.media.map(media=>this.mediaData(media))}}});
      if(resetsReview)await tx.productReviewEvent.create({data:{productId:id,actorId:userId,fromStatus:current.status,toStatus:"DRAFT",reason:"关键商品资料已修改，需要重新审核"}});
      await tx.auditLog.create({data:{actorId:userId,action:"product.draft.updated",targetType:"Product",targetId:id}});return this.detailTx(tx,store.id,id);
    });}catch(error){this.rethrow(error);}}
  async archive(userId:string,id:string){const store=await this.store(userId);const product=await this.prisma.product.findFirst({where:{id,storeId:store.id}});if(!product)throw new NotFoundException("PRODUCT_NOT_FOUND");if(!["DRAFT","REJECTED","APPROVED","INACTIVE"].includes(product.status))throw new BadRequestException("PRODUCT_CANNOT_BE_ARCHIVED");await this.transition(userId,id,product.status,"ARCHIVED","product.archived");return{archived:true};}

  async submit(userId:string,id:string){const store=await this.store(userId);const product=await this.prisma.product.findFirst({where:{id,storeId:store.id},include:{skus:{where:{isActive:true}},media:true}});if(!product)throw new NotFoundException("PRODUCT_NOT_FOUND");if(!["DRAFT","REJECTED"].includes(product.status))throw new BadRequestException("PRODUCT_CANNOT_BE_SUBMITTED");const missing:string[]=[];if(!product.categoryId)missing.push("categoryId");if(!product.descriptionZhCn?.trim())missing.push("descriptionZhCn");if(!product.skus.length)missing.push("skus");if(product.skus.some(sku=>sku.priceAmount<=0))missing.push("sku.priceAmount");if(!product.media.some(media=>media.kind==="IMAGE"&&media.isCover))missing.push("media.cover");if(missing.length)throw new BadRequestException(`PRODUCT_REVIEW_INCOMPLETE:${missing.join(",")}`);return this.transition(userId,id,product.status,"PENDING_REVIEW","product.submitted");}
  async publish(userId:string,id:string){const store=await this.store(userId);if(!store.isOpen)throw new BadRequestException("STORE_IS_CLOSED");const product=await this.prisma.product.findFirst({where:{id,storeId:store.id},include:{skus:{where:{isActive:true},include:{inventory:true}}}});if(!product)throw new NotFoundException("PRODUCT_NOT_FOUND");if(!["APPROVED","INACTIVE"].includes(product.status))throw new BadRequestException("PRODUCT_NOT_APPROVED");if(!product.skus.some(sku=>(sku.inventory?.onHand??0)-(sku.inventory?.reserved??0)>0))throw new BadRequestException("PRODUCT_HAS_NO_AVAILABLE_STOCK");return this.transition(userId,id,product.status,"ACTIVE","product.published");}
  async unpublish(userId:string,id:string){const store=await this.store(userId);const product=await this.prisma.product.findFirst({where:{id,storeId:store.id}});if(!product)throw new NotFoundException("PRODUCT_NOT_FOUND");if(product.status!=="ACTIVE")throw new BadRequestException("PRODUCT_NOT_ACTIVE");return this.transition(userId,id,"ACTIVE","INACTIVE","product.unpublished");}
  async copy(userId:string,id:string){const store=await this.store(userId);const source=await this.prisma.product.findFirst({where:{id,storeId:store.id},include:{tags:true,skus:{where:{isActive:true}},media:true}});if(!source)throw new NotFoundException("PRODUCT_NOT_FOUND");return this.prisma.$transaction(async tx=>{const copied=await tx.product.create({data:{storeId:store.id,titleZhCn:`${source.titleZhCn}（副本）`,titleEnUs:source.titleEnUs,descriptionZhCn:source.descriptionZhCn,descriptionEnUs:source.descriptionEnUs,categoryId:source.categoryId,brandId:source.brandId,franchiseId:source.franchiseId,characterId:source.characterId,material:source.material,scale:source.scale,manufacturer:source.manufacturer,copyrightNotice:source.copyrightNotice,tags:{connect:source.tags.map(tag=>({id:tag.id}))},skus:{create:source.skus.map(sku=>({nameZhCn:sku.nameZhCn,nameEnUs:sku.nameEnUs,barcode:null,optionValues:sku.optionValues??Prisma.JsonNull,weightGrams:sku.weightGrams,lengthMm:sku.lengthMm,widthMm:sku.widthMm,heightMm:sku.heightMm,priceAmount:sku.priceAmount,currency:sku.currency,code:`MC-${randomUUID().slice(0,8).toUpperCase()}`,inventory:{create:{onHand:0}}}))},media:{create:source.media.map(media=>({fileId:media.fileId,kind:media.kind,altZhCn:media.altZhCn,altEnUs:media.altEnUs,sortOrder:media.sortOrder,isCover:media.isCover}))}}});const inventories=await tx.inventory.findMany({where:{sku:{productId:copied.id}}});if(inventories.length)await tx.inventoryLedgerEntry.createMany({data:inventories.map(inventory=>({inventoryId:inventory.id,type:"INITIAL_STOCK" as const,onHandDelta:0,reservedDelta:0,onHandAfter:0,reservedAfter:0,reason:"复制商品创建 SKU",actorId:userId}))});await tx.auditLog.create({data:{actorId:userId,action:"product.copied",targetType:"Product",targetId:copied.id,metadata:{sourceId:id}}});return this.detailTx(tx,store.id,copied.id);});}

  async reviewQueue(status?:string):Promise<ProductDraftListItem[]>{const allowed=["PENDING_REVIEW","APPROVED","REJECTED"] as const;const selected=allowed.includes(status as typeof allowed[number])?status as typeof allowed[number]:"PENDING_REVIEW";const products=await this.prisma.product.findMany({where:{status:selected},include:{category:true,skus:{where:{isActive:true},include:{inventory:true}},media:true},orderBy:{updatedAt:"asc"}});return products.map(item=>{const prices=item.skus.map(sku=>sku.priceAmount);return{id:item.id,titleZhCn:item.titleZhCn,titleEnUs:item.titleEnUs??undefined,status:item.status,categoryName:item.category?.nameZhCn,skuCount:item.skus.length,priceMin:prices.length?Math.min(...prices):undefined,priceMax:prices.length?Math.max(...prices):undefined,stock:item.skus.reduce((sum,sku)=>sum+(sku.inventory?.onHand??0),0),coverFileId:item.media.find(media=>media.isCover)?.fileId,updatedAt:item.updatedAt.toISOString()};});}
  async reviewDetail(id:string):Promise<ProductReviewDetail>{const item=await this.prisma.product.findUnique({where:{id},include:{store:true,tags:true,skus:{where:{isActive:true},include:{inventory:true},orderBy:{createdAt:"asc"}},media:{orderBy:{sortOrder:"asc"}},reviewEvents:{orderBy:{createdAt:"desc"}}}});if(!item)throw new NotFoundException("PRODUCT_NOT_FOUND");return{...this.view(item),storeName:item.store.name,reviewEvents:item.reviewEvents.map(event=>this.reviewEventView(event))};}
  async decide(reviewerId:string,id:string,approved:boolean,reason:string|undefined,fieldFeedback:Array<{field:string;message:string}>){const product=await this.prisma.product.findUnique({where:{id}});if(!product)throw new NotFoundException("PRODUCT_NOT_FOUND");if(product.status!=="PENDING_REVIEW")throw new BadRequestException("PRODUCT_NOT_PENDING_REVIEW");if(!approved&&!reason?.trim()&&!fieldFeedback.length)throw new BadRequestException("REJECTION_FEEDBACK_REQUIRED");const next=approved?"APPROVED":"REJECTED";return this.prisma.$transaction(async tx=>{const updated=await tx.product.updateMany({where:{id,status:"PENDING_REVIEW"},data:{status:next}});if(!updated.count)throw new ConflictException("PRODUCT_ALREADY_REVIEWED");await tx.productReviewEvent.create({data:{productId:id,actorId:reviewerId,fromStatus:"PENDING_REVIEW",toStatus:next,reason:reason?.trim()||null,fieldFeedback:fieldFeedback as unknown as Prisma.InputJsonValue}});await tx.auditLog.create({data:{actorId:reviewerId,action:approved?"product.review.approved":"product.review.rejected",targetType:"Product",targetId:id,metadata:{reason,fieldFeedback}}});return{status:next};});}

  private transition(actorId:string,productId:string,fromStatus:ProductRecord["status"],toStatus:ProductRecord["status"],action:string){if(!canTransitionProduct(fromStatus,toStatus))throw new BadRequestException("INVALID_PRODUCT_STATUS_TRANSITION");return this.prisma.$transaction(async tx=>{const updated=await tx.product.updateMany({where:{id:productId,status:fromStatus},data:{status:toStatus}});if(!updated.count)throw new ConflictException("PRODUCT_STATUS_CHANGED");await tx.productReviewEvent.create({data:{productId,actorId,fromStatus,toStatus}});await tx.auditLog.create({data:{actorId,action,targetType:"Product",targetId:productId}});return{status:toStatus};});}
  private reviewEventView(event:{id:string;actorId:string;fromStatus:ProductRecord["status"];toStatus:ProductRecord["status"];reason:string|null;fieldFeedback:Prisma.JsonValue|null;createdAt:Date}){return{id:event.id,actorId:event.actorId,fromStatus:event.fromStatus,toStatus:event.toStatus,reason:event.reason??undefined,fieldFeedback:Array.isArray(event.fieldFeedback)?event.fieldFeedback as unknown as Array<{field:string;message:string}>:[],createdAt:event.createdAt.toISOString()};}
  private productData(dto:SaveProductDraftDto){return{titleZhCn:dto.titleZhCn,titleEnUs:dto.titleEnUs||null,descriptionZhCn:dto.descriptionZhCn||null,descriptionEnUs:dto.descriptionEnUs||null,categoryId:dto.categoryId||null,brandId:dto.brandId||null,franchiseId:dto.franchiseId||null,characterId:dto.characterId||null,material:dto.material||null,scale:dto.scale||null,manufacturer:dto.manufacturer||null,copyrightNotice:dto.copyrightNotice||null};}
  private skuData(sku:SaveProductDraftDto["skus"][number]){return{code:sku.code?.trim()||`MC-${randomUUID().slice(0,8).toUpperCase()}`,nameZhCn:sku.nameZhCn,nameEnUs:sku.nameEnUs||null,barcode:sku.barcode||null,optionValues:sku.optionValues as Prisma.InputJsonValue,weightGrams:sku.weightGrams??null,lengthMm:sku.lengthMm??null,widthMm:sku.widthMm??null,heightMm:sku.heightMm??null,priceAmount:sku.priceAmount,currency:(sku.currency||"CNY").toUpperCase()};}
  private mediaData(media:SaveProductDraftDto["media"][number]){return{fileId:media.fileId,kind:media.kind,altZhCn:media.altZhCn||null,altEnUs:media.altEnUs||null,sortOrder:media.sortOrder,isCover:media.isCover};}
  private async validate(merchantOrUserId:string,dto:SaveProductDraftDto){const merchantId=(await this.prisma.merchant.findUnique({where:{id:merchantOrUserId},select:{id:true}}))?.id??(await this.prisma.merchantMember.findFirstOrThrow({where:{userId:merchantOrUserId}})).merchantId;if(dto.media.filter(item=>item.isCover).length>1)throw new BadRequestException("PRODUCT_MEDIA_MULTIPLE_COVERS");const customCodes=dto.skus.map(item=>item.code?.trim()).filter((code):code is string=>Boolean(code));if(new Set(customCodes).size!==customCodes.length)throw new BadRequestException("DUPLICATE_SKU_CODE");const [category,brand,franchise,character,tags]=await Promise.all([dto.categoryId?this.prisma.category.count({where:{id:dto.categoryId,isActive:true}}):1,dto.brandId?this.prisma.brand.count({where:{id:dto.brandId,isActive:true}}):1,dto.franchiseId?this.prisma.franchise.count({where:{id:dto.franchiseId,isActive:true}}):1,dto.characterId?this.prisma.character.count({where:{id:dto.characterId,isActive:true,...(dto.franchiseId?{franchiseId:dto.franchiseId}:{})}}):1,this.prisma.tag.count({where:{id:{in:dto.tagIds},isActive:true}})]);if(!category||!brand||!franchise||!character||tags!==dto.tagIds.length)throw new BadRequestException("INVALID_PRODUCT_CATALOG_REFERENCE");if(dto.media.length){const members=await this.prisma.merchantMember.findMany({where:{merchantId},select:{userId:true}});const fileIds=dto.media.map(item=>item.fileId);const files=await this.prisma.fileAsset.findMany({where:{id:{in:fileIds},ownerId:{in:members.map(member=>member.userId)},purpose:"product-media",status:{notIn:["DELETED","QUARANTINED"]}},select:{id:true}});if(files.length!==fileIds.length)throw new BadRequestException("INVALID_PRODUCT_MEDIA");}}
  private async store(userId:string){const member=await this.prisma.merchantMember.findFirst({where:{userId},include:{merchant:{include:{store:true}}}});if(!member?.merchant.store||member.merchant.status!=="ACTIVE")throw new ForbiddenException("ACTIVE_MERCHANT_STORE_REQUIRED");return member.merchant.store;}
  private async detailTx(tx:Prisma.TransactionClient,storeId:string,id:string){const item=await tx.product.findFirstOrThrow({where:{id,storeId},include:{tags:true,skus:{where:{isActive:true},include:{inventory:true},orderBy:{createdAt:"asc"}},media:{orderBy:{sortOrder:"asc"}}}});return this.view(item);}
  private view(item:ProductRecord):ProductDraftView{return{id:item.id,storeId:item.storeId,status:item.status,titleZhCn:item.titleZhCn,titleEnUs:item.titleEnUs??undefined,descriptionZhCn:item.descriptionZhCn??undefined,descriptionEnUs:item.descriptionEnUs??undefined,categoryId:item.categoryId??undefined,brandId:item.brandId??undefined,franchiseId:item.franchiseId??undefined,characterId:item.characterId??undefined,tagIds:item.tags.map(tag=>tag.id),material:item.material??undefined,scale:item.scale??undefined,manufacturer:item.manufacturer??undefined,copyrightNotice:item.copyrightNotice??undefined,skus:item.skus.map(sku=>({id:sku.id,code:sku.code,nameZhCn:sku.nameZhCn,nameEnUs:sku.nameEnUs??undefined,barcode:sku.barcode??undefined,optionValues:(sku.optionValues as Record<string,string>|null)??{},weightGrams:sku.weightGrams??undefined,lengthMm:sku.lengthMm??undefined,widthMm:sku.widthMm??undefined,heightMm:sku.heightMm??undefined,priceAmount:sku.priceAmount,currency:sku.currency,initialStock:sku.inventory?.onHand??0})),media:item.media.map(media=>({id:media.id,fileId:media.fileId,kind:media.kind as "IMAGE"|"VIDEO",altZhCn:media.altZhCn??undefined,altEnUs:media.altEnUs??undefined,sortOrder:media.sortOrder,isCover:media.isCover})),createdAt:item.createdAt.toISOString(),updatedAt:item.updatedAt.toISOString()};}
  private rethrow(error:unknown):never{if(error instanceof Prisma.PrismaClientKnownRequestError&&error.code==="P2002")throw new ConflictException("SKU_CODE_ALREADY_USED");throw error;}
}

type ProductRecord=Prisma.ProductGetPayload<{include:{tags:true;skus:{include:{inventory:true}};media:true}}>;
