-- CreateTable
CREATE TABLE `AfterSale` (
    `id` VARCHAR(191) NOT NULL,
    `afterSaleNumber` VARCHAR(32) NOT NULL,
    `userId` VARCHAR(191) NOT NULL,
    `orderId` CHAR(36) NOT NULL,
    `orderItemId` CHAR(36) NOT NULL,
    `merchantOrderId` VARCHAR(191) NOT NULL,
    `merchantId` VARCHAR(191) NOT NULL,
    `storeId` VARCHAR(191) NOT NULL,
    `type` ENUM('REFUND_ONLY', 'RETURN_REFUND') NOT NULL,
    `status` ENUM('REQUESTED', 'APPROVED', 'REJECTED', 'AWAITING_RETURN', 'RETURNED', 'REFUND_PROCESSING', 'COMPLETED', 'CANCELLED') NOT NULL DEFAULT 'REQUESTED',
    `reason` VARCHAR(200) NOT NULL,
    `description` VARCHAR(2000) NOT NULL,
    `refundAmount` DECIMAL(10, 2) NOT NULL,
    `evidence` JSON NOT NULL,
    `returnCarrier` VARCHAR(40) NULL,
    `returnTrackingNumber` VARCHAR(80) NULL,
    `returnShippedAt` DATETIME(3) NULL,
    `merchantNote` VARCHAR(1000) NULL,
    `platformNote` VARCHAR(1000) NULL,
    `completedAt` DATETIME(3) NULL,
    `cancelledAt` DATETIME(3) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `AfterSale_afterSaleNumber_key`(`afterSaleNumber`),
    INDEX `AfterSale_userId_orderItemId_idx`(`userId`, `orderItemId`),
    INDEX `AfterSale_userId_createdAt_idx`(`userId`, `createdAt`),
    INDEX `AfterSale_merchantId_status_createdAt_idx`(`merchantId`, `status`, `createdAt`),
    INDEX `AfterSale_orderId_idx`(`orderId`),
    INDEX `AfterSale_orderItemId_idx`(`orderItemId`),
    UNIQUE INDEX `AfterSale_userId_orderItemId_key`(`userId`, `orderItemId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
