<script setup lang="ts">
import { onMounted, ref } from "vue";
import type { AdminButtonPermission, OrderStatus } from "@moecraft/shared";
import { UiBadge, UiButton, UiTable, type UiTableColumn } from "@moecraft/ui";
import { useOrderManagement } from "../composables/useOrderManagement";
const props=withDefaults(defineProps<{buttonPermissions?:AdminButtonPermission[]}>(),{buttonPermissions:()=>[]});
const state=useOrderManagement(),note=ref("");
const canManage=props.buttonPermissions.includes("orders.manage");
const statuses:Array<{value:OrderStatus|"";label:string}>=[{value:"",label:"全部状态"},{value:"PENDING_PAYMENT",label:"待支付"},{value:"PAID",label:"待发货"},{value:"PARTIALLY_SHIPPED",label:"部分发货"},{value:"SHIPPED",label:"已发货"},{value:"COMPLETED",label:"已完成"},{value:"CANCELLED",label:"已取消"},{value:"AFTER_SALE",label:"售后中"},{value:"CLOSED",label:"已关闭"}];
const columns:UiTableColumn[]=[{key:"order",label:"订单"},{key:"buyer",label:"买家"},{key:"stores",label:"店铺"},{key:"amount",label:"应付",align:"right"},{key:"payment",label:"支付"},{key:"status",label:"状态"},{key:"actions",label:"操作",align:"right"}];
async function open(id:string){await state.open(id);note.value=state.selected.value?.merchantOrders[0]?.merchantNote??"";}
async function save(){const child=state.selected.value?.merchantOrders[0];if(child&&note.value.trim())await state.saveNote(child.id,note.value);}
const tone=(status:string)=>status==="SUCCEEDED"||status==="COMPLETED"?"success":status==="FAILED"||status==="CANCELLED"?"danger":"warning";
onMounted(state.load);
</script>
<template><section class="orders"><div class="filters"><input v-model="state.search.value" placeholder="搜索订单号"><select v-model="state.status.value"><option v-for="item in statuses" :key="item.value" :value="item.value">{{item.label}}</option></select><UiButton variant="secondary" @click="state.load">查询</UiButton><UiButton variant="secondary" :disabled="state.busy.value" @click="state.createExport">异步导出 CSV</UiButton></div>
<p v-if="state.error.value" class="notice">{{state.error.value}}</p><div v-if="state.loading.value" class="loading">正在加载订单…</div><UiTable v-else :columns="columns" :rows="state.orders.value.map(row=>({...row,paymentStatus:row.payment.status,order:row.id,buyer:row.id,stores:row.id,amount:row.id,actions:row.id}))" empty-text="没有符合条件的订单">
<template #cell-order="{row}"><b>{{row.orderNumber}}</b><small>{{new Date(String(row.createdAt)).toLocaleString()}}</small></template>
<template #cell-buyer="{row}"><span>{{row.buyerDisplayName}}</span><small>{{row.buyerMaskedPhone}}</small></template><template #cell-stores="{row}">{{Array.isArray(row.storeNames)?row.storeNames.join(" / "):""}}</template>
<template #cell-amount="{row}"><b>¥{{row.payableAmount}}</b></template><template #cell-payment="{row}"><UiBadge :tone="tone(String(row.paymentStatus))">{{row.paymentStatus}}</UiBadge></template><template #cell-status="{row}"><UiBadge :tone="tone(String(row.status))">{{row.status}}</UiBadge></template><template #cell-actions="{row}"><UiButton size="sm" variant="ghost" @click="open(String(row.id))">详情</UiButton></template></UiTable>
<Teleport to="body"><div v-if="state.selected.value" class="overlay" @click.self="state.selected.value=null"><aside><header><div><small>{{state.selected.value.orderNumber}}</small><h2>{{state.selected.value.status}}</h2></div><button @click="state.selected.value=null">×</button></header><dl><dt>买家</dt><dd>{{state.selected.value.buyerDisplayName}} · {{state.selected.value.address.phone}}</dd><dt>地址</dt><dd>{{state.selected.value.address.province}} {{state.selected.value.address.city}} {{state.selected.value.address.district}} {{state.selected.value.address.addressLine}}</dd><dt>支付事实</dt><dd>{{state.selected.value.payment.status}} · ¥{{state.selected.value.payment.amount}} · {{state.selected.value.payment.provider}}</dd></dl><section v-for="child in state.selected.value.merchantOrders" :key="child.id"><h3>{{child.storeName}}</h3><p v-for="item in child.items" :key="item.id">{{item.productTitle}} × {{item.quantity}} <b>¥{{item.payableAmount}}</b></p></section><label v-if="canManage&&state.selected.value.merchantOrders.length">商家内部备注<textarea v-model="note" maxlength="1000"/></label><UiButton v-if="canManage&&state.selected.value.merchantOrders.length" :disabled="state.busy.value||!note.trim()" @click="save">保存备注</UiButton><p class="readonly">支付事实仅由支付回调更新，运营页面不可修改。</p></aside></div></Teleport></section></template>
<style scoped lang="less">
.orders{padding:20px;border:1px solid var(--border);border-radius:8px;background:var(--surface)}.filters{display:flex;gap:10px;margin-bottom:16px}.filters input,.filters select{padding:9px 11px;border:1px solid var(--border);border-radius:8px;background:var(--surface-raised);color:var(--text)}.filters input{flex:1}.notice{padding:10px;border-radius:8px;background:var(--accent-soft);color:var(--accent)}td b,td small{display:block}td small{margin-top:4px;color:var(--text-muted)}.loading{padding:50px;text-align:center}.overlay{position:fixed;z-index:50;inset:0;display:grid;justify-content:end;background:#0006}.overlay aside{width:min(94vw,620px);height:100vh;overflow:auto;padding:28px;background:var(--surface);box-shadow:var(--shadow)}.overlay header{display:flex;justify-content:space-between}.overlay header button{border:0;background:none;color:var(--text);font-size:28px}.overlay dl{display:grid;grid-template-columns:100px 1fr;gap:9px}.overlay dd{margin:0;color:var(--text)}.overlay section{padding:14px 0;border-top:1px solid var(--border)}.overlay section p{display:flex;justify-content:space-between}.overlay label{display:grid;gap:7px}.overlay textarea{min-height:100px;padding:10px}.readonly{color:var(--text-muted);font-size:11px}@media(max-width:700px){.filters{flex-direction:column}}
</style>
