import { BadRequestException, ConflictException, ForbiddenException, Injectable, NotFoundException } from "@nestjs/common";
import type { MerchantMemberView, StaffInvitationView, StoreProfileView, StoreReturnAddress } from "@moecraft/shared";
import { Prisma } from "@prisma/client";
import { PrismaService } from "../prisma/prisma.service";
import type { InviteStaffDto, SaveStoreProfileDto, UpdateMemberRoleDto } from "./store.dto";

@Injectable()
export class StoreService {
  constructor(private readonly prisma: PrismaService) {}

  async mine(userId: string) { const merchant = await this.requireMerchant(userId); const store = await this.prisma.store.findUnique({ where: { merchantId: merchant.id } }); return store ? this.storeView(store, merchant.status) : null; }
  async save(userId: string, dto: SaveStoreProfileDto): Promise<StoreProfileView> {
    const merchant = await this.requireMerchant(userId, true); await this.validateMedia(userId, [dto.logoFileId, dto.bannerFileId].filter((id): id is string => Boolean(id)));
    const returnAddress: Prisma.InputJsonObject = { ...dto.returnAddress };
    const data = { name: dto.name, slug: dto.slug, logoFileId: dto.logoFileId ?? null, bannerFileId: dto.bannerFileId ?? null, description: dto.description ?? null, customerServiceEmail: dto.customerServiceEmail ?? null, customerServicePhone: dto.customerServicePhone ?? null, returnAddress, isOpen: dto.isOpen };
    try { const store = await this.prisma.$transaction(async (tx) => { const saved = await tx.store.upsert({ where: { merchantId: merchant.id }, update: data, create: { ...data, merchantId: merchant.id } }); await tx.auditLog.create({ data: { actorId: userId, action: "store.profile.updated", targetType: "Store", targetId: saved.id } }); return saved; }); return this.storeView(store, merchant.status); } catch (error) { if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2002") throw new ConflictException("STORE_SLUG_ALREADY_USED"); throw error; }
  }
  async publicBySlug(slug: string): Promise<StoreProfileView> { const store = await this.prisma.store.findFirst({ where: { slug, isOpen: true, merchant: { status: "ACTIVE" } }, include: { merchant: true } }); if (!store) throw new NotFoundException("STORE_NOT_FOUND"); return this.storeView(store, store.merchant.status); }

  async members(userId: string): Promise<MerchantMemberView[]> { const merchant = await this.requireMerchant(userId); const members = await this.prisma.merchantMember.findMany({ where: { merchantId: merchant.id }, include: { user: true }, orderBy: [{ role: "asc" }, { createdAt: "asc" }] }); return members.map((item) => ({ id:item.id,userId:item.userId,username:item.user.username,displayName:item.user.displayName,role:item.role,createdAt:item.createdAt.toISOString() })); }
  async invite(userId: string, dto: InviteStaffDto): Promise<StaffInvitationView> { const merchant = await this.requireMerchant(userId, true); const invitee = await this.prisma.user.findUnique({ where: { username: dto.username } }); if (!invitee?.isActive) throw new NotFoundException("INVITEE_NOT_FOUND"); if (await this.prisma.merchantMember.findUnique({ where: { merchantId_userId: { merchantId: merchant.id, userId: invitee.id } } })) throw new ConflictException("ALREADY_MERCHANT_MEMBER"); const pending = await this.prisma.staffInvitation.findFirst({ where: { merchantId:merchant.id,inviteeId:invitee.id,status:"PENDING",expiresAt:{gt:new Date()} } }); if (pending) throw new ConflictException("INVITATION_ALREADY_PENDING"); const invitation = await this.prisma.staffInvitation.create({ data: { merchantId:merchant.id,inviteeId:invitee.id,invitedById:userId,role:dto.role,expiresAt:new Date(Date.now()+7*24*60*60*1000) } }); return this.invitationView(invitation, merchant.name, invitee.displayName); }
  async invitationsMine(userId: string): Promise<StaffInvitationView[]> { const items = await this.prisma.staffInvitation.findMany({ where:{inviteeId:userId,status:"PENDING",expiresAt:{gt:new Date()}},include:{merchant:true,invitee:true},orderBy:{createdAt:"desc"} }); return items.map((item)=>this.invitationView(item,item.merchant.name,item.invitee.displayName)); }
  async acceptInvitation(userId: string, id: string) { const invitation = await this.prisma.staffInvitation.findUnique({ where:{id} }); if (!invitation || invitation.inviteeId!==userId || invitation.status!=="PENDING" || invitation.expiresAt<=new Date()) throw new NotFoundException("INVITATION_NOT_FOUND"); await this.prisma.$transaction(async(tx)=>{await tx.merchantMember.upsert({where:{merchantId_userId:{merchantId:invitation.merchantId,userId}},update:{role:invitation.role},create:{merchantId:invitation.merchantId,userId,role:invitation.role}});await tx.staffInvitation.update({where:{id},data:{status:"ACCEPTED"}});await tx.userRole.upsert({where:{userId_role:{userId,role:invitation.role==="OWNER"?"MERCHANT_OWNER":"MERCHANT_STAFF"}},update:{},create:{userId,role:invitation.role==="OWNER"?"MERCHANT_OWNER":"MERCHANT_STAFF"}});}); return {accepted:true}; }
  async updateRole(userId:string,memberId:string,dto:UpdateMemberRoleDto){const merchant=await this.requireMerchant(userId,true);const member=await this.member(merchant.id,memberId);if(member.role==="OWNER"&&dto.role!=="OWNER")await this.assertAnotherOwner(merchant.id,member.id);await this.prisma.merchantMember.update({where:{id:member.id},data:{role:dto.role}});return {updated:true};}
  async removeMember(userId:string,memberId:string){const merchant=await this.requireMerchant(userId,true);const member=await this.member(merchant.id,memberId);if(member.role==="OWNER")await this.assertAnotherOwner(merchant.id,member.id);await this.prisma.merchantMember.delete({where:{id:member.id}});return {removed:true};}

  private async requireMerchant(userId:string,owner=false){const membership=await this.prisma.merchantMember.findFirst({where:{userId,...(owner?{role:"OWNER"}:{})},include:{merchant:true}});if(!membership)throw new ForbiddenException("MERCHANT_ACCESS_REQUIRED");return membership.merchant;}
  private async member(merchantId:string,id:string){const item=await this.prisma.merchantMember.findFirst({where:{id,merchantId}});if(!item)throw new NotFoundException("MERCHANT_MEMBER_NOT_FOUND");return item;}
  private async assertAnotherOwner(merchantId:string,excludeId:string){if(await this.prisma.merchantMember.count({where:{merchantId,role:"OWNER",id:{not:excludeId}}})<1)throw new BadRequestException("LAST_MERCHANT_OWNER_REQUIRED");}
  private async validateMedia(ownerId:string,ids:string[]){if(!ids.length)return;const count=await this.prisma.fileAsset.count({where:{id:{in:ids},ownerId,purpose:"store-media",status:{notIn:["DELETED","QUARANTINED"]}}});if(count!==ids.length)throw new BadRequestException("INVALID_STORE_MEDIA");}
  private storeView(store:{id:string;merchantId:string;name:string;slug:string;logoFileId:string|null;bannerFileId:string|null;description:string|null;customerServiceEmail:string|null;customerServicePhone:string|null;returnAddress:Prisma.JsonValue|null;isOpen:boolean;updatedAt:Date},merchantStatus:"ACTIVE"|"SUSPENDED"|"CLOSED"):StoreProfileView{return{...store,returnAddress:store.returnAddress as StoreReturnAddress|null,merchantStatus,updatedAt:store.updatedAt.toISOString()};}
  private invitationView(item:{id:string;merchantId:string;inviteeId:string;role:"OWNER"|"STAFF";status:"PENDING"|"ACCEPTED"|"CANCELLED";expiresAt:Date},merchantName:string,inviteeName:string):StaffInvitationView{return{...item,merchantName,inviteeName,expiresAt:item.expiresAt.toISOString()};}
}
