<script setup lang="ts">
import { onMounted,watch } from "vue";
import { UiButton,UiPageContainer,UiPageHeader,UiTable,type UiTableColumn } from "@moecraft/ui";
import type { AdminButtonPermission } from "@moecraft/shared";
import ProductReviewDrawer from "./components/ProductReviewDrawer.vue";
import { useProductReviews } from "./composables/useProductReviews";
const props=withDefaults(defineProps<{buttonPermissions?:AdminButtonPermission[]}>(),{buttonPermissions:()=>[]});
const review=useProductReviews();const columns:UiTableColumn[]=[{key:"title",label:"商品",width:"34%"},{key:"status",label:"状态",width:"16%"},{key:"sku",label:"SKU / 库存",width:"20%"},{key:"updated",label:"提交时间",width:"18%"},{key:"actions",label:"操作",width:"12%",align:"right"}];
watch(review.status,review.load);onMounted(review.load);
</script>
<template><UiPageContainer size="full" class="review-page content-scroll"><UiPageHeader eyebrow="PRODUCT GOVERNANCE" title="商品审核" description="审核商家提交的商品资料、规格、媒体与版权信息，所有决定保留可追溯记录。"><template #actions><select v-model="review.status.value"><option value="PENDING_REVIEW">待审核</option><option value="APPROVED">已通过</option><option value="REJECTED">已驳回</option></select><UiButton variant="secondary" @click="review.load">刷新</UiButton></template></UiPageHeader><p v-if="review.error.value" class="error">{{review.error.value}}</p><section class="panel"><div v-if="review.loading.value" class="loading">正在加载审核队列…</div><UiTable v-else :columns="columns" :rows="review.items.value.map(item=>({...item,title:item.titleZhCn,sku:item.skuCount,updated:item.updatedAt,actions:item.id}))" empty-text="当前没有待处理商品"><template #cell-title="{row}"><div class="title"><b>{{row.titleZhCn}}</b><small>{{row.categoryName||'未分类'}}</small></div></template><template #cell-status="{row}"><em>{{row.status}}</em></template><template #cell-sku="{row}">{{row.skuCount}} 个 / {{row.stock}} 件</template><template #cell-updated="{row}">{{new Date(row.updatedAt as string).toLocaleString()}}</template><template #cell-actions="{row}"><UiButton size="sm" @click="review.open(row.id as string)">审核</UiButton></template></UiTable></section><Teleport to="body"><ProductReviewDrawer v-if="review.selected.value" :product="review.selected.value" :reason="review.reason.value" :field-feedback="review.fieldFeedback.value" :busy="review.busy.value" :can-review="props.buttonPermissions.includes('products.review')" @update:reason="review.reason.value=$event" @add-feedback="review.addFeedback" @remove-feedback="review.fieldFeedback.value.splice($event,1)" @approve="review.decide(true)" @reject="review.decide(false)" @close="review.selected.value=null"/></Teleport></UiPageContainer></template>
<style scoped lang="less">.review-page{background:var(--app-bg)}select{padding:9px 12px;border:1px solid var(--border);border-radius:9px;background:var(--surface);color:var(--text)}.panel{padding:20px;margin-top:18px;border:1px solid var(--border);border-radius:18px;background:var(--surface);box-shadow:var(--shadow)}.title{display:grid}.title b{color:var(--text)}.title small{margin-top:4px;color:var(--text-muted)}em{padding:5px 8px;border-radius:99px;background:var(--accent-soft);color:var(--accent);font-size:9px;font-style:normal}.error{padding:12px;border-radius:10px;background:#ffe4eb;color:#be3c59}.loading{padding:50px;text-align:center}</style>
