import { computed, reactive, ref } from "vue";
import type { CatalogOverview, ProductDraftInput, ProductDraftListItem, ProductReviewDetail, ProductReviewEventView, ProductStatus } from "@moecraft/shared";
import { apiRequest } from "../../../../api";

const emptyDraft=():ProductDraftInput=>({titleZhCn:"",titleEnUs:"",descriptionZhCn:"",descriptionEnUs:"",categoryId:"",brandId:"",franchiseId:"",characterId:"",tagIds:[],material:"",scale:"",manufacturer:"",copyrightNotice:"",skus:[],media:[]});

export function useProductManagement(){
  const products=ref<ProductDraftListItem[]>([]);const catalog=ref<CatalogOverview|null>(null);const reviewEvents=ref<ProductReviewEventView[]>([]);const editingStatus=ref<ProductStatus>("DRAFT");const loading=ref(false);const busy=ref(false);const error=ref("");const keyword=ref("");const status=ref("ALL");const drawerOpen=ref(false);const editingId=ref<string|null>(null);const form=reactive<ProductDraftInput>(emptyDraft());
  const editable=computed(()=>!editingId.value||["DRAFT","REJECTED","APPROVED","INACTIVE"].includes(editingStatus.value));
  const filtered=computed(()=>products.value.filter(item=>(status.value==="ALL"||item.status===status.value)&&`${item.titleZhCn} ${item.titleEnUs??""}`.toLowerCase().includes(keyword.value.toLowerCase())));
  function reset(value:ProductDraftInput=emptyDraft()){Object.assign(form,emptyDraft(),structuredClone({titleZhCn:value.titleZhCn,titleEnUs:value.titleEnUs,descriptionZhCn:value.descriptionZhCn,descriptionEnUs:value.descriptionEnUs,categoryId:value.categoryId,brandId:value.brandId,franchiseId:value.franchiseId,characterId:value.characterId,tagIds:value.tagIds,material:value.material,scale:value.scale,manufacturer:value.manufacturer,copyrightNotice:value.copyrightNotice,skus:value.skus,media:value.media}));}
  function payload():ProductDraftInput{return{titleZhCn:form.titleZhCn,titleEnUs:form.titleEnUs,descriptionZhCn:form.descriptionZhCn,descriptionEnUs:form.descriptionEnUs,categoryId:form.categoryId,brandId:form.brandId,franchiseId:form.franchiseId,characterId:form.characterId,tagIds:[...form.tagIds],material:form.material,scale:form.scale,manufacturer:form.manufacturer,copyrightNotice:form.copyrightNotice,skus:form.skus.map(({id:_,...sku})=>({...sku,optionValues:{...sku.optionValues}})),media:form.media.map(({id:_,...media})=>({...media}))};}
  async function load(){loading.value=true;error.value="";try{[products.value,catalog.value]=await Promise.all([apiRequest<ProductDraftListItem[]>("/merchant/products"),apiRequest<CatalogOverview>("/catalog/public")]);}catch(e){error.value=message(e,"商品数据加载失败");}finally{loading.value=false;}}
  function create(){editingId.value=null;editingStatus.value="DRAFT";reviewEvents.value=[];reset();drawerOpen.value=true;}
  async function edit(id:string){busy.value=true;try{const item=await apiRequest<ProductReviewDetail>(`/merchant/products/${id}`);editingId.value=id;editingStatus.value=item.status;reviewEvents.value=item.reviewEvents;reset(item);drawerOpen.value=true;}catch(e){error.value=message(e,"商品读取失败");}finally{busy.value=false;}}
  async function save(){if(!form.titleZhCn.trim()){error.value="请填写必填项：中文标题。";return;}const incomplete=form.skus.findIndex(item=>!item.nameZhCn.trim());if(incomplete>=0){error.value=`请填写第 ${incomplete+1} 个 SKU 的规格名称。`;return;}busy.value=true;error.value="";try{await apiRequest(editingId.value?`/merchant/products/${editingId.value}`:"/merchant/products",{method:editingId.value?"PUT":"POST",body:JSON.stringify(payload())});drawerOpen.value=false;await load();}catch(e){error.value=message(e,"草稿保存失败");}finally{busy.value=false;}}
  async function action(id:string,name:"submit"|"publish"|"unpublish"|"copy"){busy.value=true;error.value="";try{await apiRequest(`/merchant/products/${id}/${name}`,{method:"POST"});await load();}catch(e){error.value=message(e,"商品状态操作失败");}finally{busy.value=false;}}
  async function archive(id:string){if(!confirm("确定归档这个商品？"))return;busy.value=true;try{await apiRequest(`/merchant/products/${id}`,{method:"DELETE"});await load();}catch(e){error.value=message(e,"归档失败");}finally{busy.value=false;}}
  return{products,catalog,reviewEvents,editingStatus,editable,loading,busy,error,keyword,status,drawerOpen,editingId,form,filtered,load,create,edit,save,action,archive};
}
function message(error:unknown,fallback:string){return(error as{message?:string})?.message??fallback;}
