import { computed, reactive, ref } from "vue";
import type { CatalogOverview, ProductDraftInput, ProductDraftListItem, ProductReviewDetail, ProductReviewEventView, ProductStatus } from "@moecraft/shared";
import { apiRequest } from "../../../../api";
import { useLocale, type MessageKey } from "../../../../i18n";

function newSku(){return{code:`MC-${crypto.randomUUID().slice(0,8).toUpperCase()}`,nameZhCn:"",optionValues:{},priceAmount:0,currency:"CNY",initialStock:0};}
function newMedia(sortOrder=0){return{fileId:"",kind:"IMAGE" as const,sortOrder,isCover:sortOrder===0};}
function requiredNumber(value:unknown){return Number(value);}
function optionalNumber(value:unknown){return value===""||value===undefined||value===null?undefined:Number(value);}
const emptyDraft=():ProductDraftInput=>({titleZhCn:"",titleEnUs:"",descriptionZhCn:"",descriptionEnUs:"",categoryId:"",brandId:"",franchiseId:"",characterId:"",tagIds:[],material:"",scale:"",manufacturer:"",copyrightNotice:"",saleType:"IN_STOCK",presaleNotice:"",shippingWindowStart:"",shippingWindowEnd:"",afterSalesSummary:"",skus:[newSku()],media:[newMedia()]});
type ProductReviewMissingField="categoryId"|"descriptionZhCn"|"skus"|"sku.priceAmount"|"media.cover"|"presaleNotice"|"shippingWindow";
const reviewFieldLabels:Record<ProductReviewMissingField,MessageKey>={categoryId:"products.category",descriptionZhCn:"products.descriptionZhCn",skus:"products.skuSection","sku.priceAmount":"products.priceCents","media.cover":"products.setCover",presaleNotice:"products.presaleNotice",shippingWindow:"products.shippingWindow"};
function getProductReviewMissingFields(product:ProductReviewDetail):ProductReviewMissingField[]{const missing:ProductReviewMissingField[]=[];if(!product.categoryId)missing.push("categoryId");if(!product.descriptionZhCn?.trim())missing.push("descriptionZhCn");if(!product.skus.length)missing.push("skus");if(product.skus.some((sku)=>sku.priceAmount<=0))missing.push("sku.priceAmount");if(!product.media.some((media)=>media.kind==="IMAGE"&&media.isCover))missing.push("media.cover");if(product.saleType==="PREORDER"){if(!product.presaleNotice?.trim())missing.push("presaleNotice");if(!product.shippingWindowStart||!product.shippingWindowEnd||product.shippingWindowStart>product.shippingWindowEnd)missing.push("shippingWindow");}return missing;}

export function useProductManagement(){
  const { locale, t } = useLocale();
  const products=ref<ProductDraftListItem[]>([]);const catalog=ref<CatalogOverview|null>(null);const reviewEvents=ref<ProductReviewEventView[]>([]);const editingStatus=ref<ProductStatus>("DRAFT");const loading=ref(false);const busy=ref(false);const error=ref("");const keyword=ref("");const status=ref("ALL");const drawerOpen=ref(false);const editingId=ref<string|null>(null);const form=reactive<ProductDraftInput>(emptyDraft());
  const editable=computed(()=>!editingId.value||["DRAFT","REJECTED","APPROVED","INACTIVE"].includes(editingStatus.value));
  const filtered=computed(()=>products.value.filter(item=>(status.value==="ALL"||item.status===status.value)&&`${item.titleZhCn} ${item.titleEnUs??""}`.toLowerCase().includes(keyword.value.toLowerCase())));
  function reset(value:ProductDraftInput=emptyDraft()){const defaults=emptyDraft();Object.assign(form,defaults,structuredClone({titleZhCn:value.titleZhCn,titleEnUs:value.titleEnUs,descriptionZhCn:value.descriptionZhCn,descriptionEnUs:value.descriptionEnUs,categoryId:value.categoryId,brandId:value.brandId,franchiseId:value.franchiseId,characterId:value.characterId,tagIds:value.tagIds,material:value.material,scale:value.scale,manufacturer:value.manufacturer,copyrightNotice:value.copyrightNotice,saleType:value.saleType,presaleNotice:value.presaleNotice,shippingWindowStart:value.shippingWindowStart?.slice(0,10),shippingWindowEnd:value.shippingWindowEnd?.slice(0,10),afterSalesSummary:value.afterSalesSummary,skus:value.skus.length?value.skus:defaults.skus,media:value.media.length?value.media:defaults.media}));}
  function payload():ProductDraftInput{return{titleZhCn:form.titleZhCn,titleEnUs:form.titleEnUs,descriptionZhCn:form.descriptionZhCn,descriptionEnUs:form.descriptionEnUs,categoryId:form.categoryId,brandId:form.brandId,franchiseId:form.franchiseId,characterId:form.characterId,tagIds:[...form.tagIds],material:form.material,scale:form.scale,manufacturer:form.manufacturer,copyrightNotice:form.copyrightNotice,saleType:form.saleType,presaleNotice:form.presaleNotice,shippingWindowStart:form.shippingWindowStart,shippingWindowEnd:form.shippingWindowEnd,afterSalesSummary:form.afterSalesSummary,skus:form.skus.map((sku)=>({...sku,optionValues:{...sku.optionValues},weightGrams:optionalNumber(sku.weightGrams),lengthMm:optionalNumber(sku.lengthMm),widthMm:optionalNumber(sku.widthMm),heightMm:optionalNumber(sku.heightMm),priceAmount:requiredNumber(sku.priceAmount),initialStock:requiredNumber(sku.initialStock)})),media:form.media.map(({id:_,...media})=>({...media,sortOrder:requiredNumber(media.sortOrder)}))};}
  async function load(){loading.value=true;error.value="";try{[products.value,catalog.value]=await Promise.all([apiRequest<ProductDraftListItem[]>("/merchant/products"),apiRequest<CatalogOverview>("/catalog/public")]);}catch(e){error.value=message(e,t("products.error.load"));}finally{loading.value=false;}}
  function create(){editingId.value=null;editingStatus.value="DRAFT";reviewEvents.value=[];error.value="";reset();drawerOpen.value=true;}
  async function edit(id:string){busy.value=true;error.value="";try{const item=await apiRequest<ProductReviewDetail>(`/merchant/products/${id}`);editingId.value=id;editingStatus.value=item.status;reviewEvents.value=item.reviewEvents;reset(item);drawerOpen.value=true;}catch(e){error.value=message(e,t("products.error.read"));}finally{busy.value=false;}}
  function setSaveError(value:string){error.value=value;}
  async function save(){if(!form.titleZhCn.trim()){setSaveError(t("products.error.titleRequired"));return;}const incomplete=form.skus.findIndex(item=>!item.nameZhCn.trim());if(incomplete>=0){setSaveError(t("products.error.skuNameRequired",{index:incomplete+1}));return;}busy.value=true;error.value="";try{await apiRequest(editingId.value?`/merchant/products/${editingId.value}`:"/merchant/products",{method:editingId.value?"PUT":"POST",body:JSON.stringify(payload())});drawerOpen.value=false;await load();}catch(e){setSaveError(message(e,t("products.error.save")));}finally{busy.value=false;}}
  async function action(id:string,name:"submit"|"publish"|"unpublish"|"copy"){busy.value=true;error.value="";try{if(name==="submit"){const product=await apiRequest<ProductReviewDetail>(`/merchant/products/${id}`);const missing=getProductReviewMissingFields(product);if(missing.length){error.value=t("products.error.reviewIncomplete",{fields:missing.map((field)=>t(reviewFieldLabels[field])).join(locale.value==="en-US" ? ", " : "、")});return;}}await apiRequest(`/merchant/products/${id}/${name}`,{method:"POST"});await load();}catch(e){error.value=message(e,t("products.error.action"));}finally{busy.value=false;}}
  async function archive(id:string){if(!confirm(t("products.archiveConfirm")))return;busy.value=true;try{await apiRequest(`/merchant/products/${id}`,{method:"DELETE"});await load();}catch(e){error.value=message(e,t("products.error.archive"));}finally{busy.value=false;}}
  return{products,catalog,reviewEvents,editingStatus,editable,loading,busy,error,keyword,status,drawerOpen,editingId,form,filtered,load,create,edit,save,action,archive};
}
function message(error:unknown,fallback:string){return(error as{message?:string})?.message??fallback;}
